package com.adinfi.formateador.view.designer;

import com.adinfi.formateador.bos.ModuleBO;
import com.adinfi.formateador.dao.TemplateDAO;
import com.adinfi.formateador.main.MainView;
import com.adinfi.formateador.util.ApplicationProperties;
import com.adinfi.formateador.util.GlobalDefines;
import com.adinfi.formateador.util.ThumbTemplate;
import com.adinfi.formateador.util.Utilerias;
import com.adinfi.formateador.view.PanelThumb;
import java.awt.BorderLayout;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.time.Clock;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;

/**
 *
 * @author USUARIO
 */
public final class Designer extends javax.swing.JPanel {

    public enum SELECTED_COMPONENT {

        TEXT,
        MULTIMEDIA,
        BULLET
    }

    private CustomScrollRule scrollRule;
    private SpinnerNumberModel numSpin;
    private String nameModuleSearch = "";
    private int HEIGHT_MODEL = 26;
    private final int HEIGHT_MIN = 0;
    private final int HEIGHT_MAX = 26;
    private final int HEIGHT_MAX_FP = 20;
    private final int WIDTH_MODEL_PX = 580;
    private final int HEIGHT_MODEL_PX = 720;
    private final int DPI = 72;
    private int deleteModuleId;
    private ModuleBO moduleBO;
    public int pxToComplete;
    public int IdModuloCreado;
    private DesignerModuleDialog dialog;
    private boolean isActive;
    private boolean isFirstPage = false;

    /**
     * Creates new form Designer
     */
    public Designer() {
        initComponents();
        populatePanel();
        txtCM.setVisible(false);
        jButton8.setVisible(false);
        jButton4.setVisible(false);
        jLabel3.setVisible(false);
        jButton9.setVisible(false);
        txtModuleName.setVisible(false);
        jButton5.setVisible(false);
        btnPrev.setVisible(false);
        isActive = true;
    }

    public Designer(DesignerModuleDialog dialog) {
        initComponents();
        populatePanel();
        this.dialog = dialog;
        txtCM.setVisible(false);
        jButton8.setVisible(false);
        jButton4.setVisible(false);
        jLabel3.setVisible(false);
        jButton9.setVisible(false);
        txtModuleName.setVisible(false);
        jButton5.setVisible(false);
        btnPrev.setVisible(false);
        toggleBullet.setContentAreaFilled(false);
        toggleMultimedia.setContentAreaFilled(false);
        toggleText.setContentAreaFilled(false);
        isActive = true;
    }

    public void loadPageToCompleteTemplate() {

        if (pxToComplete > 0) {
            HEIGHT_MODEL = (int) Math.round(pxToComplete * 25.4 / 10 / DPI);;
        } else {
            if (isFirstPage) {
                HEIGHT_MODEL = HEIGHT_MAX_FP;
            } else {
                HEIGHT_MODEL = HEIGHT_MAX;
            }

        }
        createTemplate();
    }

    protected void populatePanel() {
        MainView.main.getProgressBar().setIndeterminate(true);
        MainView.main.getProgressBar().setVisible(true);
        PopulatePanelWorker worker = new PopulatePanelWorker();
        worker.execute();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel4 = new javax.swing.JLabel();
        northPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtModuleName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        txtCM = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        firstPage = new javax.swing.JCheckBox();
        southPanel = new javax.swing.JPanel();
        btnPrev = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        eastPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        toggleText = new javax.swing.JToggleButton();
        toggleMultimedia = new javax.swing.JToggleButton();
        toggleBullet = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        westPanel = new javax.swing.JPanel();
        moduleNorthPanel = new javax.swing.JPanel();
        scrollPanelModules = new javax.swing.JScrollPane();
        moduleCenterPanel = new javax.swing.JPanel();
        centerPanel = new javax.swing.JPanel();
        splitPanel = new javax.swing.JSplitPane();
        previewPanel = new javax.swing.JPanel();

        jLabel4.setText("jLabel4");
        jLabel4.setName("jLabel4"); // NOI18N

        setLayout(new java.awt.BorderLayout());

        northPanel.setName("northPanel"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setText("Nombre:");
        jLabel1.setName("jLabel1"); // NOI18N

        txtModuleName.setName("txtModuleName"); // NOI18N

        jLabel3.setText("Altura cm.");
        jLabel3.setName("jLabel3"); // NOI18N

        jButton8.setText("Crear");
        jButton8.setToolTipText("Crear módulo");
        jButton8.setName("jButton8"); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        txtCM.setEnabled(false);
        txtCM.setName("txtCM"); // NOI18N
        txtCM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCMKeyPressed(evt);
            }
        });

        jButton4.setText("Deshacer");
        jButton4.setToolTipText("Deshacer");
        jButton4.setEnabled(false);
        jButton4.setName("jButton4"); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextField2.setName("jTextField2"); // NOI18N
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar_cat.png"))); // NOI18N
        jButton7.setName("jButton7"); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        firstPage.setText("Primera Hoja");
        firstPage.setName("firstPage"); // NOI18N
        firstPage.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                firstPageItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 260, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtModuleName, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstPage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCM, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jButton8)
                    .addComponent(txtCM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModuleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstPage))
                .addContainerGap())
        );

        javax.swing.GroupLayout northPanelLayout = new javax.swing.GroupLayout(northPanel);
        northPanel.setLayout(northPanelLayout);
        northPanelLayout.setHorizontalGroup(
            northPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(northPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        northPanelLayout.setVerticalGroup(
            northPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, northPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(northPanel, java.awt.BorderLayout.PAGE_START);

        southPanel.setName("southPanel"); // NOI18N

        btnPrev.setText("Previsualizar");
        btnPrev.setName("btnPrev"); // NOI18N
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });
        southPanel.add(btnPrev);

        jButton5.setText("Editar");
        jButton5.setName("jButton5"); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        southPanel.add(jButton5);

        jButton9.setText("Guardar");
        jButton9.setName("jButton9"); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        southPanel.add(jButton9);

        jButton1.setText("Nuevo");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        southPanel.add(jButton1);

        jButton2.setText("Cancelar");
        jButton2.setEnabled(false);
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        southPanel.add(jButton2);

        jButton3.setText("Eliminar");
        jButton3.setEnabled(false);
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        southPanel.add(jButton3);

        add(southPanel, java.awt.BorderLayout.SOUTH);

        eastPanel.setName("eastPanel"); // NOI18N

        jPanel2.setName("jPanel2"); // NOI18N

        toggleText.setBackground(new java.awt.Color(202, 201, 198));
        buttonGroup1.add(toggleText);
        toggleText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/texto_icon.png"))); // NOI18N
        toggleText.setMaximumSize(new java.awt.Dimension(70, 40));
        toggleText.setMinimumSize(new java.awt.Dimension(70, 40));
        toggleText.setName("toggleText"); // NOI18N
        toggleText.setPreferredSize(new java.awt.Dimension(70, 40));

        toggleMultimedia.setBackground(new java.awt.Color(254, 106, 0));
        buttonGroup1.add(toggleMultimedia);
        toggleMultimedia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/multimedia_icon.png"))); // NOI18N
        toggleMultimedia.setSelected(true);
        toggleMultimedia.setMaximumSize(new java.awt.Dimension(70, 40));
        toggleMultimedia.setMinimumSize(new java.awt.Dimension(70, 40));
        toggleMultimedia.setName("toggleMultimedia"); // NOI18N
        toggleMultimedia.setPreferredSize(new java.awt.Dimension(70, 40));

        toggleBullet.setBackground(new java.awt.Color(35, 81, 130));
        buttonGroup1.add(toggleBullet);
        toggleBullet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bullet_icon.png"))); // NOI18N
        toggleBullet.setMaximumSize(new java.awt.Dimension(70, 40));
        toggleBullet.setMinimumSize(new java.awt.Dimension(70, 40));
        toggleBullet.setName("toggleBullet"); // NOI18N
        toggleBullet.setPreferredSize(new java.awt.Dimension(70, 40));

        jLabel6.setText("Texto");
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setText("Multimedia");
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setText("Bullet");
        jLabel8.setName("jLabel8"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(toggleBullet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                        .addComponent(toggleMultimedia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(toggleText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(toggleText, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(toggleMultimedia, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(toggleBullet, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setText("Tool Box");
        jLabel5.setName("jLabel5"); // NOI18N

        javax.swing.GroupLayout eastPanelLayout = new javax.swing.GroupLayout(eastPanel);
        eastPanel.setLayout(eastPanelLayout);
        eastPanelLayout.setHorizontalGroup(
            eastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eastPanelLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(eastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eastPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eastPanelLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        eastPanelLayout.setVerticalGroup(
            eastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eastPanelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(eastPanel, java.awt.BorderLayout.EAST);

        westPanel.setName("westPanel"); // NOI18N

        moduleNorthPanel.setName("moduleNorthPanel"); // NOI18N
        moduleNorthPanel.setPreferredSize(new java.awt.Dimension(155, 10));

        javax.swing.GroupLayout moduleNorthPanelLayout = new javax.swing.GroupLayout(moduleNorthPanel);
        moduleNorthPanel.setLayout(moduleNorthPanelLayout);
        moduleNorthPanelLayout.setHorizontalGroup(
            moduleNorthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 208, Short.MAX_VALUE)
        );
        moduleNorthPanelLayout.setVerticalGroup(
            moduleNorthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        scrollPanelModules.setName("scrollPanelModules"); // NOI18N

        moduleCenterPanel.setName("moduleCenterPanel"); // NOI18N
        moduleCenterPanel.setLayout(new java.awt.GridLayout(0, 1));
        scrollPanelModules.setViewportView(moduleCenterPanel);

        javax.swing.GroupLayout westPanelLayout = new javax.swing.GroupLayout(westPanel);
        westPanel.setLayout(westPanelLayout);
        westPanelLayout.setHorizontalGroup(
            westPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(westPanelLayout.createSequentialGroup()
                .addComponent(moduleNorthPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(westPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(scrollPanelModules, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        westPanelLayout.setVerticalGroup(
            westPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(westPanelLayout.createSequentialGroup()
                .addComponent(moduleNorthPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(scrollPanelModules, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE))
        );

        add(westPanel, java.awt.BorderLayout.WEST);

        centerPanel.setName("centerPanel"); // NOI18N
        centerPanel.setLayout(new java.awt.BorderLayout());

        splitPanel.setDividerLocation(0);
        splitPanel.setName("splitPanel"); // NOI18N

        previewPanel.setName("previewPanel"); // NOI18N
        previewPanel.setLayout(new java.awt.BorderLayout());
        splitPanel.setRightComponent(previewPanel);

        centerPanel.add(splitPanel, java.awt.BorderLayout.CENTER);

        add(centerPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        createTemplate();
        jButton4.setEnabled(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        //JOptionPane.showMessageDialog(this, "Error al guardar módulo", Utilerias.getProperty(ApplicationProperties.APP_TITLE), JOptionPane.ERROR_MESSAGE);
        //scrollRule.getCellPanel().genThumbs();

        if (scrollRule == null || scrollRule.getCellPanel() == null) {
            JOptionPane.showMessageDialog(this, "No se ha diseñado el módulo, debe crear uno para guardar.");
        } else if (scrollRule.getCellPanel().getViewEditMsg()) {
            int result = JOptionPane.showConfirmDialog(this, "¿Desea realizar una copia del módulo actual?.", Utilerias.getProperty(ApplicationProperties.APP_TITLE), JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION) {
                moduleBO = null;
                scrollRule.getCellPanel().setViewEditMsg(false);
            } else {
                jButton2.setEnabled(false);
                jButton9.setVisible(false);

                txtModuleName.setText("");
                jButton7.setVisible(true);
                jTextField2.setVisible(true);
                txtModuleName.setVisible(false);

                jButton1.setVisible(true);
                moduleCenterPanel.setEnabled(true);
                moduleNorthPanel.setEnabled(true);
                
                // ALTURAX
                HEIGHT_MODEL = HEIGHT_MIN;
                
                createTemplate();
                return;
            }
        }

        int modId = 0;
        if (moduleBO != null && moduleBO.getModuleId() > 0) {
            modId = moduleBO.getModuleId();
        }

        if (txtModuleName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre del módulo es obligatorio.");
        } else if (Utilerias.isRepeated(Utilerias.TablesValueNames.MODULE_NEW.name(),
                Utilerias.TablesValueNames.MODULE_NEW.getCaption(), txtModuleName.getText(), "MODULE_ID", modId)) {
            JOptionPane.showMessageDialog(null, "El nombre " + txtModuleName.getText() + " ya existe, ingrese uno diferente.");
        } else {
            if (scrollRule.getCellPanel().validateModule(txtModuleName.getText(), modId)) {
                firstPage.setEnabled(true);
                firstPage.setSelected(false);
                IdModuloCreado = scrollRule.getCellPanel().IdModuloCreado;
                txtModuleName.setVisible(false);
                jButton2.setEnabled(false);
                jButton9.setVisible(false);
                txtModuleName.setText("");
                jButton1.setVisible(true);
                jButton7.setVisible(true);
                jTextField2.setVisible(true);

                moduleCenterPanel.setEnabled(true);
                moduleNorthPanel.setEnabled(true);

                HEIGHT_MODEL = HEIGHT_MIN;
                createTemplate();

                nameModuleSearch = jTextField2.getText();
                populatePanel();
                previewPanel.removeAll();
                if (pxToComplete > 0 && IdModuloCreado > 0) {
                    if (dialog != null) {
                        dialog.dispose();
                    }
                }
            }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void txtCMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCMKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            createTemplate();
        }
    }//GEN-LAST:event_txtCMKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //saveTemplate();
       
        
        txtModuleName.setEnabled(true);
        txtCM.setEnabled(true);
        jButton8.setEnabled(true);
        jButton2.setEnabled(true);
        jButton9.setVisible(true);
        firstPage.setEnabled(false);

        txtModuleName.setText("");
        txtCM.setText("0");
        txtModuleName.setVisible(true);
        jButton7.setVisible(false);
        jTextField2.setVisible(false);
        txtModuleName.requestFocusInWindow();

        jButton1.setVisible(false);
        moduleCenterPanel.setEnabled(false);
        moduleNorthPanel.setEnabled(false);

        if (pxToComplete > 0) {
            HEIGHT_MODEL = (int) Math.round(pxToComplete * 25.4 / 10 / DPI);
        } else {
            if(isFirstPage){
                HEIGHT_MODEL = HEIGHT_MAX_FP;
            }else{
                HEIGHT_MODEL = HEIGHT_MAX;
            }
        }

        createTemplate();
        scrollRule.getCellPanel().setShowContexMenu(true);
        //btnPrev.setVisible(true);
        previewPanel.removeAll();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        nameModuleSearch = jTextField2.getText();
        populatePanel();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        scrollRule.getCellPanel().deshacer();
        centerPanel.updateUI();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int result = 0;
        if (jButton9.isVisible()) {
            result = JOptionPane.showConfirmDialog(this, "Se perderan todo lo que ha hecho hasta ahora que no guardo. ¿Esta seguro de continuar?.", Utilerias.getProperty(ApplicationProperties.APP_TITLE), JOptionPane.YES_NO_OPTION);
        } else {
            result = JOptionPane.YES_OPTION;
        }

        if (result == JOptionPane.YES_OPTION) {
            jButton2.setEnabled(false);
            jButton9.setVisible(false);
            jButton5.setVisible(false);
            jButton3.setEnabled(false);

            txtModuleName.setText("");
            jButton7.setVisible(true);
            jTextField2.setVisible(true);
            txtModuleName.setVisible(false);

            jButton1.setVisible(true);
            moduleCenterPanel.setEnabled(true);
            moduleNorthPanel.setEnabled(true);

            HEIGHT_MODEL = HEIGHT_MIN;
            //btnPrev.setVisible(false);
            createTemplate();
            previewPanel.removeAll();
        }
        
            firstPage.setEnabled(true);
            firstPage.setSelected(false);


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField2FocusLost

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (deleteModuleId > 0) {
            int result = JOptionPane.showConfirmDialog(this, "¿Está seguro de eliminar el módulo?.", Utilerias.getProperty(ApplicationProperties.APP_TITLE), JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION) {
                TemplateDAO tempDAO = new TemplateDAO();
                int val = tempDAO.validaEliminacionModulo(deleteModuleId);
                boolean res = val != TemplateDAO.DELETE_TEMPLATE;
                if (res) {
                    if (val == TemplateDAO.USED_TEMPLATE) {
                        JOptionPane.showMessageDialog(this, "El módulo no se puede eliminar, ya que está siendo usado por un documento.");
                    } else if (val == TemplateDAO.INTO_TEMPLATE) {
                        JOptionPane.showMessageDialog(this, "El módulo no se puede eliminar, ya que está siendo usado por una plantilla.");
                    }
                    deleteModuleId = 0;
                } else {
                    res = tempDAO.removeModule(deleteModuleId);
                    if (!res) {
                        JOptionPane.showMessageDialog(this, "Ocurrió un error al eliminar.");
                    } else {
                        JOptionPane.showMessageDialog(this, "El módulo se eliminó satisfactoriamente.");
                        firstPage.setEnabled(true);
                        deleteModuleId = 0;
                        nameModuleSearch = "";
                        jButton3.setEnabled(false);
                        jButton5.setVisible(false);
                        jButton1.setVisible(true);
                        nameModuleSearch = jTextField2.getText();
                        populatePanel();
                        HEIGHT_MODEL = HEIGHT_MIN;
                        //btnPrev.setVisible(false);
                        createTemplate();
                        previewPanel.removeAll();
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un módulo para eliminar.");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        firstPage.setEnabled(false);
        jButton5.setVisible(false);
        jButton9.setVisible(true);
        jButton2.setEnabled(true);
        jButton3.setEnabled(false);
        jButton7.setVisible(false);
        jTextField2.setVisible(false);
        txtModuleName.setVisible(true);
        scrollRule.getCellPanel().setEditMode(true);
        scrollRule.getCellPanel().setShowContexMenu(true);
        moduleCenterPanel.setEnabled(false);
        txtModuleName.requestFocusInWindow();
        genPreview();

    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:+
        int screenHeight = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height - 600;
        ThumbTemplate thTemp = new ThumbTemplate();
        BufferedImage image = thTemp.genThumbPrev(scrollRule.getCellPanel(), (short) 90, (short) 90);
        JLabel label = new JLabel(new ImageIcon(image.getScaledInstance(580 + (screenHeight - 720), screenHeight, Image.SCALE_SMOOTH)));
        previewPanel.removeAll();
        previewPanel.setLayout(new BorderLayout());
        previewPanel.add(label, BorderLayout.CENTER);
        previewPanel.revalidate();
        previewPanel.updateUI();
//        JFrame f = new JFrame();
//        f.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
//        f.getContentPane().add(label);
//        f.pack();
//        f.setAlwaysOnTop(true);
//        f.setTitle("Visualizador de Modulo");
//        Utilerias.centreFrame(f, true);
//        f.setVisible(true);
    }//GEN-LAST:event_btnPrevActionPerformed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            nameModuleSearch = jTextField2.getText();
            populatePanel();
        }
    }//GEN-LAST:event_jTextField2KeyPressed

    private void firstPageItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_firstPageItemStateChanged
        isFirstPage = firstPage.isSelected();
    }//GEN-LAST:event_firstPageItemStateChanged

    public void genPreview() {
        // TODO add your handling code here:+
        ThumbTemplate thTemp = new ThumbTemplate();
        BufferedImage image = thTemp.genThumbPrev(scrollRule.getCellPanel(), (short) 90, (short) 90);

        int hr = 0;
        if (pxToComplete > 0) {
            hr = pxToComplete;
        } else {
            hr = HEIGHT_MODEL_PX;
        }

        JLabel label = new JLabel(new ImageIcon(image.getScaledInstance((WIDTH_MODEL_PX / 3), (hr / 3), Image.SCALE_SMOOTH)));
        previewPanel.removeAll();
        previewPanel.setLayout(new BorderLayout());
        previewPanel.add(label, BorderLayout.CENTER);
        previewPanel.revalidate();
        previewPanel.updateUI();

    }

    protected void createTemplate() {

        String moduleName = txtModuleName.getText();

        //int heightModule = HEIGHT_MODEL_MAL;
        scrollRule = new CustomScrollRule(HEIGHT_MODEL, this, pxToComplete);
        /*
         centerPanel.removeAll();
         centerPanel.add(scrollRule, BorderLayout.CENTER);
         centerPanel.revalidate();
         centerPanel.updateUI();
         */

        splitPanel.setLeftComponent(scrollRule);
        splitPanel.revalidate();
        splitPanel.updateUI();

        setMaximuxSizeFromEditor();
    }

    private void setMaximuxSizeFromEditor() {

        int width = scrollRule.getCellPanel().getWidth();
        System.out.println(width);
        int w = splitPanel.getWidth();
        splitPanel.setDividerLocation(w);
    }

    public static SELECTED_COMPONENT getSelectedComponent() {
        SELECTED_COMPONENT selected = SELECTED_COMPONENT.TEXT;
        if (toggleText.isSelected()) {
            selected = SELECTED_COMPONENT.TEXT;
        } else if (toggleMultimedia.isSelected()) {
            selected = SELECTED_COMPONENT.MULTIMEDIA;
        } else if (toggleBullet.isSelected()) {
            selected = SELECTED_COMPONENT.BULLET;
        }
        return selected;
    }

    protected void saveTemplate() {
        String moduleName = txtModuleName.getText();
        if (moduleName == null || moduleName.isEmpty() == true) {
            JOptionPane.showMessageDialog(this, "Nombre de módulo requerido", Utilerias.getProperty(ApplicationProperties.APP_TITLE), JOptionPane.INFORMATION_MESSAGE);
        } else {
            //Continuar con el guardado del módulo 

        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrev;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JPanel eastPanel;
    private javax.swing.JCheckBox firstPage;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel moduleCenterPanel;
    private javax.swing.JPanel moduleNorthPanel;
    private javax.swing.JPanel northPanel;
    private javax.swing.JPanel previewPanel;
    private javax.swing.JScrollPane scrollPanelModules;
    private javax.swing.JPanel southPanel;
    private javax.swing.JSplitPane splitPanel;
    private static javax.swing.JToggleButton toggleBullet;
    private static javax.swing.JToggleButton toggleMultimedia;
    private static javax.swing.JToggleButton toggleText;
    private javax.swing.JTextField txtCM;
    private javax.swing.JTextField txtModuleName;
    private javax.swing.JPanel westPanel;
    // End of variables declaration//GEN-END:variables

    class PopulatePanelWorker extends SwingWorker<ModuleBO, ModuleBO> {

        private boolean exist = false;

        PopulatePanelWorker() {
        }

        @Override
        protected ModuleBO doInBackground() {
            try {
                TemplateDAO tempDAO = new TemplateDAO();
                List<ModuleBO> lstModules = tempDAO.getModules();

                for (ModuleBO moduleBO : lstModules) {
                    if (nameModuleSearch.isEmpty()) {
                        String fileName
                                = new StringBuilder(Utilerias.getFilePath(Utilerias.PATH_TYPE.THUMB_MODULE_DIR))
                                .append(moduleBO.getModuleId())
                                .append(".")
                                .append(GlobalDefines.png).toString();
                        moduleBO.setTemplatePath(fileName);
                        
                                SwingUtilities.invokeLater(new Runnable() {
                        @Override
                        public void run() {
                    if (!new File(moduleBO.getTemplatePath()).exists()) {
                                ThumbTemplate thTemp = new ThumbTemplate();
                                short hres = 30;
                                if (moduleBO.getHeight() > 350) {
                                    hres = 90;
                                }

                                thTemp.genThumbModule(moduleBO.getModuleId(), (short) 90, hres, "");
                                thTemp.genThumbModule(moduleBO.getModuleId(), moduleBO.getWidth(), moduleBO.getHeight(), "_B");
                            }
                        }
                    });
                        
                        
                        publish(moduleBO);
                        exist = true;
                    } else if (moduleBO.getName().toUpperCase().contains(nameModuleSearch.toUpperCase())) {
                        String fileName
                                = new StringBuilder(Utilerias.getFilePath(Utilerias.PATH_TYPE.THUMB_MODULE_DIR))
                                .append(moduleBO.getModuleId())
                                .append(".")
                                .append(GlobalDefines.png).toString();
                        moduleBO.setTemplatePath(fileName);
                        publish(moduleBO);
                        exist = true;
                        //break;
                    }
                }
                if (exist == false && false == nameModuleSearch.isEmpty()) {
                    publish((ModuleBO) null);
                }
            } catch (Exception ex) {
                Utilerias.logger(getClass()).error(ex);
            }
            return null;
        }

        @Override
        public void process(List<ModuleBO> chunks) {

            try {
                moduleCenterPanel.removeAll();
                if (chunks == null) {
                    return;
                }

                for (int i = 0; i < chunks.size(); i++) {
                    try {
                        final ModuleBO modBO = chunks.get(i);

                        PanelThumb pan = new PanelThumb(modBO.getModuleId(), PanelThumb.DEFAULT_WIDTH_PANEL_SIZE, PanelThumb.DEFAULT_HEIGHT_PANEL_SIZE, modBO.getTemplatePath(), modBO.getName());
                        pan.getButton().addMouseListener(new MouseAdapter() {

                            @Override
                            public void mouseClicked(MouseEvent me) {
                                if (me.getClickCount() == GlobalDefines.DEFAULT_CLICK_COUNT && !jButton9.isVisible()) {
                                    deleteModuleId = modBO.getModuleId();
                                    jButton3.setEnabled(true);
                                    HEIGHT_MODEL = HEIGHT_MAX;
                                    createTemplate();
                                    TemplateDAO templateDAO = new TemplateDAO();
                                    moduleBO = templateDAO.getModule(deleteModuleId);
                                    txtModuleName.setText(moduleBO.getName());
                                    scrollRule.getCellPanel().viewModule(moduleBO.getRootSection().getChildSectionsAsList());
                                    scrollRule.getCellPanel().setEditMode(false);
                                    centerPanel.updateUI();
                                    jButton1.setVisible(false);
                                    jButton5.setVisible(true);
                                    jButton2.setEnabled(true);
                                    //btnPrev.setVisible(true);
                                    previewPanel.removeAll();
                                } else {
                                    deleteModuleId = 0;
                                }
                            }
                        });
                        moduleCenterPanel.add(pan);
                        moduleCenterPanel.revalidate();
                        moduleCenterPanel.updateUI();
                    } catch (Exception e) {
                        Utilerias.logger(getClass()).debug(e);
                    }
                }
            } catch (Exception ex) {
                Utilerias.logger(getClass()).error(ex);
            }
        }

        @Override
        protected void done() {
            MainView.main.getProgressBar().setVisible(false);
            if (exist == false) {
                JOptionPane.showMessageDialog(null, "No se encontraron coincidencias de la búsqueda");
            }

            if (isActive) {
                HEIGHT_MODEL = HEIGHT_MIN;
                createTemplate();
            }
        }
    }

}
