package com.adinfi.formateador.view.designer;

import com.adinfi.formateador.bos.DocumentTypeBO;
import com.adinfi.formateador.bos.ModuleBO;
import com.adinfi.formateador.bos.TemplateBO;
import com.adinfi.formateador.bos.TemplateModuleBO;
import com.adinfi.formateador.dao.DocumentTypeDAO;
import com.adinfi.formateador.dao.TemplateDAO;
import com.adinfi.formateador.main.MainApp;
import com.adinfi.formateador.main.MainView;
import com.adinfi.formateador.util.ApplicationProperties;
import com.adinfi.formateador.util.GlobalDefines;
import com.adinfi.formateador.util.ThumbTemplate;
import com.adinfi.formateador.util.Utilerias;
import com.adinfi.formateador.view.PanelThumb;
import com.adinfi.formateador.view.administration.JComboCheckBox;
import com.adinfi.formateador.view.resources.CCheckBox;
import java.awt.BorderLayout;
import java.awt.Rectangle;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author USUARIO
 */
public final class TemplateDesigner extends javax.swing.JPanel {

    public enum SELECTED_COMPONENT {

        TEXT,
        MULTIMEDIA,
        BULLET
    }

    private final int HEIGHT_MODEL_PX = GlobalDefines.DRAWABLE_HEIGHT;
    private CustomScrollRuleTemplate scrollRule;
    private SpinnerNumberModel numSpin;
    //List modulos = new ArrayList();
    int hoja = 1;
    boolean titleAdded = false;
    //List<Integer> height = new ArrayList();
    private DocumentTypeBO type;
    private String filtroStr = "";
    private PopulatePanelTempWorker worker = new PopulatePanelTempWorker();
    private int editTemplateId;
    private boolean fillRes;
    private CCheckBox ccbox;
    public short totalHeight = 0;
    public short currentHeight = 0;

    public short getCurrentHeight() {
        return currentHeight;
    }

    public void setCurrentHeight(short currentHeight) {
        this.currentHeight = currentHeight;
    }

    public short getTotalHeight() {
        return totalHeight;
    }

    public void setTotalHeight(short totalHeight) {
        this.totalHeight = totalHeight;
    }

    private boolean isTitleSelectedGloabal = false;

    /**
     * Creates new form Designer
     */
    public TemplateDesigner() {
        initComponents();
        populatePanel();
        populatePanelTemp();
        scrollRule = new CustomScrollRuleTemplate(10);
        centerPanel.removeAll();
        centerPanel.add(scrollRule, BorderLayout.CENTER);
        centerPanel.revalidate();
        centerPanel.updateUI();
        save.setVisible(false);
        jButton2.setVisible(false);
        undo.setVisible(false);
        editTemplateId = 0;
        clearFields();
    }
//    
//    public TemplateDesigner(){
//    
//    }

    protected void populatePanel() {
        MainView.main.getProgressBar().setIndeterminate(true);
        MainView.main.getProgressBar().setVisible(true);
        PopulatePanelWorker worker = new PopulatePanelWorker();
        worker.execute();
        loadDocumentTypeCbo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        northPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtHeightTitulo = new javax.swing.JTextField();
        undo = new javax.swing.JButton();
        addHeightTitle = new javax.swing.JButton();
        isTitle = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        documentType = new JComboCheckBox();
        txtTemplateName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        southPanel = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        save = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        eastPanel = new javax.swing.JPanel();
        westPanel = new javax.swing.JPanel();
        moduleNorthPanel = new javax.swing.JPanel();
        btnSearchModule3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        searchModules3 = new javax.swing.JTextField();
        scrollPanelModules = new javax.swing.JScrollPane();
        moduleCenterPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        nameTemplateSearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        documentTypeSearch = new javax.swing.JComboBox();
        checkFirstPage = new javax.swing.JCheckBox();
        btnTemplateSearch = new javax.swing.JButton();
        scrollPanelTemplate = new javax.swing.JScrollPane();
        panelTemplateThums = new javax.swing.JPanel();
        centerPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        northPanel.setName("northPanel"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        jPanel3.setName("jPanel3"); // NOI18N

        jLabel4.setText("Altura Titulo");
        jLabel4.setName("jLabel4"); // NOI18N

        txtHeightTitulo.setEnabled(false);
        txtHeightTitulo.setName("txtHeightTitulo"); // NOI18N

        undo.setText("Deshacer");
        undo.setEnabled(false);
        undo.setName("undo"); // NOI18N
        undo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoActionPerformed(evt);
            }
        });

        addHeightTitle.setText("Agregar");
        addHeightTitle.setEnabled(false);
        addHeightTitle.setName("addHeightTitle"); // NOI18N
        addHeightTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHeightTitleActionPerformed(evt);
            }
        });

        isTitle.setText("Primera Hoja");
        isTitle.setName("isTitle"); // NOI18N
        isTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isTitleActionPerformed(evt);
            }
        });

        jLabel3.setText("Tipo de documento");
        jLabel3.setName("jLabel3"); // NOI18N

        documentType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));
        documentType.setEnabled(false);
        documentType.setName("documentType"); // NOI18N

        txtTemplateName.setEnabled(false);
        txtTemplateName.setName("txtTemplateName"); // NOI18N

        jLabel1.setText("Nombre de Plantilla:");
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTemplateName, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(documentType, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(isTitle)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHeightTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addHeightTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(undo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(undo)
                        .addComponent(jLabel4)
                        .addComponent(txtHeightTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addHeightTitle)
                        .addComponent(isTitle))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtTemplateName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(documentType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout northPanelLayout = new javax.swing.GroupLayout(northPanel);
        northPanel.setLayout(northPanelLayout);
        northPanelLayout.setHorizontalGroup(
            northPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        northPanelLayout.setVerticalGroup(
            northPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(northPanel, java.awt.BorderLayout.NORTH);

        southPanel.setName("southPanel"); // NOI18N

        jButton2.setText("Editar");
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        southPanel.add(jButton2);

        save.setText("Guardar");
        save.setEnabled(false);
        save.setName("save"); // NOI18N
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        southPanel.add(save);

        jButton1.setText("Nuevo");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        southPanel.add(jButton1);

        cancel.setText("Cancelar");
        cancel.setEnabled(false);
        cancel.setName("cancel"); // NOI18N
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        southPanel.add(cancel);

        jButton3.setText("Eliminar");
        jButton3.setEnabled(false);
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        southPanel.add(jButton3);

        jButton4.setText("Crear Modulo");
        jButton4.setName("jButton4"); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        southPanel.add(jButton4);

        add(southPanel, java.awt.BorderLayout.SOUTH);

        eastPanel.setName("eastPanel"); // NOI18N
        eastPanel.setPreferredSize(new java.awt.Dimension(50, 520));

        javax.swing.GroupLayout eastPanelLayout = new javax.swing.GroupLayout(eastPanel);
        eastPanel.setLayout(eastPanelLayout);
        eastPanelLayout.setHorizontalGroup(
            eastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        eastPanelLayout.setVerticalGroup(
            eastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        add(eastPanel, java.awt.BorderLayout.EAST);

        westPanel.setEnabled(false);
        westPanel.setName("westPanel"); // NOI18N

        moduleNorthPanel.setEnabled(false);
        moduleNorthPanel.setName("moduleNorthPanel"); // NOI18N

        btnSearchModule3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar_cat.png"))); // NOI18N
        btnSearchModule3.setEnabled(false);
        btnSearchModule3.setName("btnSearchModule3"); // NOI18N
        btnSearchModule3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchModule3ActionPerformed(evt);
            }
        });

        jLabel7.setText("Buscar Modulos");
        jLabel7.setName("jLabel7"); // NOI18N

        searchModules3.setEnabled(false);
        searchModules3.setName("searchModules3"); // NOI18N
        searchModules3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchModules3KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout moduleNorthPanelLayout = new javax.swing.GroupLayout(moduleNorthPanel);
        moduleNorthPanel.setLayout(moduleNorthPanelLayout);
        moduleNorthPanelLayout.setHorizontalGroup(
            moduleNorthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moduleNorthPanelLayout.createSequentialGroup()
                .addComponent(searchModules3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchModule3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(moduleNorthPanelLayout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(0, 118, Short.MAX_VALUE))
        );
        moduleNorthPanelLayout.setVerticalGroup(
            moduleNorthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moduleNorthPanelLayout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(moduleNorthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearchModule3)
                    .addComponent(searchModules3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        scrollPanelModules.setEnabled(false);
        scrollPanelModules.setName("scrollPanelModules"); // NOI18N

        moduleCenterPanel.setEnabled(false);
        moduleCenterPanel.setName("moduleCenterPanel"); // NOI18N
        moduleCenterPanel.setLayout(new java.awt.GridLayout(0, 1));
        scrollPanelModules.setViewportView(moduleCenterPanel);

        jPanel2.setName("jPanel2"); // NOI18N

        jLabel6.setText("Nombre");
        jLabel6.setName("jLabel6"); // NOI18N

        nameTemplateSearch.setName("nameTemplateSearch"); // NOI18N
        nameTemplateSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameTemplateSearchKeyPressed(evt);
            }
        });

        jLabel2.setText("Tipo de Documento");
        jLabel2.setName("jLabel2"); // NOI18N

        documentTypeSearch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        documentTypeSearch.setName("documentTypeSearch"); // NOI18N

        checkFirstPage.setText("Primera Hoja");
        checkFirstPage.setName("checkFirstPage"); // NOI18N

        btnTemplateSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar_cat.png"))); // NOI18N
        btnTemplateSearch.setName("btnTemplateSearch"); // NOI18N
        btnTemplateSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTemplateSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameTemplateSearch)
                    .addComponent(documentTypeSearch, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(checkFirstPage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(btnTemplateSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameTemplateSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(documentTypeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkFirstPage)
                    .addComponent(btnTemplateSearch))
                .addContainerGap())
        );

        scrollPanelTemplate.setName("scrollPanelTemplate"); // NOI18N

        panelTemplateThums.setName("panelTemplateThums"); // NOI18N
        panelTemplateThums.setLayout(new java.awt.GridLayout(0, 1));
        scrollPanelTemplate.setViewportView(panelTemplateThums);

        javax.swing.GroupLayout westPanelLayout = new javax.swing.GroupLayout(westPanel);
        westPanel.setLayout(westPanelLayout);
        westPanelLayout.setHorizontalGroup(
            westPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(westPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(westPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moduleNorthPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(westPanelLayout.createSequentialGroup()
                        .addGroup(westPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollPanelTemplate)
                            .addComponent(scrollPanelModules))
                        .addGap(7, 7, 7)))
                .addGap(40, 40, 40))
        );
        westPanelLayout.setVerticalGroup(
            westPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(westPanelLayout.createSequentialGroup()
                .addComponent(moduleNorthPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(scrollPanelModules, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(scrollPanelTemplate, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
        );

        add(westPanel, java.awt.BorderLayout.WEST);

        centerPanel.setName("centerPanel"); // NOI18N
        centerPanel.setLayout(new java.awt.BorderLayout());
        add(centerPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        if (scrollRule.getCellPanelTemplate().viewEditMsj) {
            int choice = JOptionPane.showConfirmDialog(null, "¿Desea realizar una copia de la plantilla actual?", "", JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.NO_OPTION) {
                enableFields(false);
                scrollRule.getCellPanelTemplate().removeAllModules();
                cancel.setEnabled(false);
                save.setEnabled(false);
                save.setVisible(false);
                jButton2.setVisible(false);
                jButton1.setVisible(true);

                nameTemplateSearch.setEnabled(true);
                documentTypeSearch.setEnabled(true);
                checkFirstPage.setEnabled(true);
                btnTemplateSearch.setEnabled(true);

                isTitle.setSelected(false);
                scrollRule.getCellPanelTemplate().showContexMenu = false;

                //modulos.clear();
                //height.clear();
                clearFields();
                //height = new ArrayList();
                scrollRule.getCellPanelTemplate().viewEditMsj = false;
                scrollRule.getCellPanelTemplate().editMode = false;
                editTemplateId = 0;
                titleAdded = false;
            } else {
                scrollRule.getCellPanelTemplate().editMode = false;
                MainView.main.getProgressBar().setIndeterminate(true);
                MainView.main.getProgressBar().setVisible(true);
                saveTemplate();
                isTitle.setEnabled(true);
                panelTemplateThums.removeAll();
                panelTemplateThums.repaint();
                worker.doInBackground();
                panelTemplateThums.revalidate();
                loadDocTypeCboSearch();
                MainView.main.getProgressBar().setVisible(false);
            }
        } else {
            MainView.main.getProgressBar().setIndeterminate(true);
            MainView.main.getProgressBar().setVisible(true);
            saveTemplate();
            panelTemplateThums.removeAll();
            panelTemplateThums.repaint();
            worker.doInBackground();
            panelTemplateThums.revalidate();
            loadDocTypeCboSearch();
            MainView.main.getProgressBar().setVisible(false);
        }
    }//GEN-LAST:event_saveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        totalHeight = 0;
        clearFields();
        isTitle.setEnabled(false);
        enableFields(true);
        cancel.setEnabled(true);
        save.setEnabled(true);
        save.setVisible(true);
        jButton1.setVisible(false);
        scrollRule.getCellPanelTemplate().showContexMenu = true;
        txtTemplateName.requestFocusInWindow();
        //height = new ArrayList();
        scrollRule.getCellPanelTemplate().viewEditMsj = false;
        editTemplateId = 0;
        titleAdded = false;
        scrollRule.getCellPanelTemplate().widthTemplateDesigner = this.getWidth();
        scrollRule.getCellPanelTemplate().heightTemplateDesigner = this.getHeight();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void undoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoActionPerformed
//        if (scrollRule.getCellPanelTemplate().getItemsPanel() > 0) {
//            scrollRule.getCellPanelTemplate().removeModules();
//            if (modulos.size() > 0) {
//                System.out.println("se removio el modulo" + modulos.get(modulos.size() - 1));
//                modulos.remove(modulos.size() - 1);
//                height.remove(height.size() - 1);
//                int totalHeight = 0;
//                for (Integer height1 : height) {
//                    totalHeight = totalHeight + height1;
//                }
//                System.out.println(height);
//                System.out.println("Total: " + totalHeight);
//                for (int j = 0; j < modulos.size(); j++) {
//                    System.out.println("\nSe agrego el modulo " + modulos.get(j).toString());
//                }
//            }
//        }
    }//GEN-LAST:event_undoActionPerformed

    private void addHeightTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHeightTitleActionPerformed
        if (scrollRule.getCellPanelTemplate().editMode && titleAdded) {
            JOptionPane.showMessageDialog(this, "La plantilla ya cuenta con un titulo.");
            return;
        }

        if (scrollRule.getCellPanelTemplate().lstModule != null) {
            for (ModuleBO mod : scrollRule.getCellPanelTemplate().lstModule) {
                if (mod.getModuleId() <= 0) {
                    JOptionPane.showMessageDialog(this, "La plantilla ya cuenta con un titulo.");
                    return;
                }
            }
        }

        if (!txtHeightTitulo.getText().isEmpty()) {

            double cm = Double.valueOf(txtHeightTitulo.getText());
            int pxVisual = 0;
            int pxReal = 0;

            if (cm > 0) {
                pxVisual = Utilerias.cmToPx(cm, 94);
                pxReal = Utilerias.cmToPx(cm, 72);

                totalHeight = 0;

                if (scrollRule.getCellPanelTemplate().lstModule != null) {
                    for (ModuleBO mBO : scrollRule.getCellPanelTemplate().lstModule) {
                        if ("Titulo".equals(mBO.getName().trim()) && mBO.getWidth() == 0) {
                            continue;
                        }
                        totalHeight += mBO.getHeight();
                    }
                }

                totalHeight += pxVisual;

                if (isTitleSelectedGloabal) {
                    if (totalHeight > GlobalDefines.DRAWABLE_HEIGHT_PH) {
                        JOptionPane.showMessageDialog(null, "La plantilla supera el alto de una hoja, Intente con un título de menor tamaño");
                        titleAdded = false;
                    } else {
                        scrollRule.getCellPanelTemplate().addModuleTemplate(-1, pxVisual);
                        titleAdded = true;
                    }
                } else {
                    if (totalHeight > GlobalDefines.DRAWABLE_HEIGHT) {
                        JOptionPane.showMessageDialog(null, "La plantilla supera el alto de una hoja, Intente con un título de menor tamaño");
                        titleAdded = false;
                    } else {
                        scrollRule.getCellPanelTemplate().addModuleTemplate(-1, pxVisual);
                        titleAdded = true;
                    }
                }

                if (scrollRule.getCellPanelTemplate().editMode) {
                    scrollRule.getCellPanelTemplate().viewEditMsj = true;
                }

            }

        }
    }//GEN-LAST:event_addHeightTitleActionPerformed


    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        int choice = JOptionPane.showConfirmDialog(null, "¿Cancelar creación de plantilla?", "", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            isTitle.setEnabled(true);
            enableFields(false);
            scrollRule.getCellPanelTemplate().removeAllModules();
            cancel.setEnabled(false);
            save.setEnabled(false);
            save.setVisible(false);
            jButton2.setVisible(false);
            jButton1.setVisible(true);

            nameTemplateSearch.setEnabled(true);
            documentTypeSearch.setEnabled(true);
            checkFirstPage.setEnabled(true);
            btnTemplateSearch.setEnabled(true);

            isTitle.setSelected(false);
            scrollRule.getCellPanelTemplate().showContexMenu = false;

            //modulos.clear();
            //height.clear();
            clearFields();
            //height = new ArrayList();
            scrollRule.getCellPanelTemplate().viewEditMsj = false;
            scrollRule.getCellPanelTemplate().editMode = false;
            editTemplateId = 0;
            titleAdded = false;
        }
    }//GEN-LAST:event_cancelActionPerformed

    private void isTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isTitleActionPerformed

        isTitleSelectedGloabal = isTitle.isSelected();

        txtHeightTitulo.setEnabled(isTitleSelectedGloabal);
        addHeightTitle.setEnabled(isTitleSelectedGloabal);

    }//GEN-LAST:event_isTitleActionPerformed

    private void btnSearchModule3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchModule3ActionPerformed
        // TODO add your handling code here:
        fillRes = false;
        filtroStr = searchModules3.getText();
        moduleCenterPanel.removeAll();
        moduleCenterPanel.repaint();
        populatePanel();
        moduleCenterPanel.revalidate();

    }//GEN-LAST:event_btnSearchModule3ActionPerformed

    private void btnTemplateSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTemplateSearchActionPerformed
        // TODO add your handling code here:
        filtroStr = nameTemplateSearch.getText();
        if (documentTypeSearch.getSelectedItem() instanceof DocumentTypeBO) {
            type = (DocumentTypeBO) documentTypeSearch.getSelectedItem();
        } else {
            type = null;
        }

        if (type != null && type.getIddocument_type() <= 0) {
            type = null;
        }

        panelTemplateThums.removeAll();
        panelTemplateThums.repaint();
        worker.doInBackground();
        panelTemplateThums.revalidate();

        if (panelTemplateThums.getComponentCount() <= 0) {
            JOptionPane.showMessageDialog(this, "No se encontraron coincidencias de la búsqueda.");
        }
    }//GEN-LAST:event_btnTemplateSearchActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.out.println(isTitleSelectedGloabal);
        isTitle.setEnabled(false);
        save.setVisible(true);
        save.setEnabled(true);
        jButton1.setVisible(false);
        cancel.setEnabled(true);
        jButton3.setEnabled(false);
        jButton2.setVisible(false);

        nameTemplateSearch.setEnabled(false);
        documentTypeSearch.setEnabled(false);
        checkFirstPage.setEnabled(false);
        btnTemplateSearch.setEnabled(false);
        txtHeightTitulo.setEnabled(true);

        enableFields(true);

        scrollRule.getCellPanelTemplate().showContexMenu = true;
        scrollRule.getCellPanelTemplate().editMode = true;
        //scrollRule.getCellPanelTemplate().viewEditMsj=true;
        txtTemplateName.requestFocusInWindow();
        scrollRule.getCellPanelTemplate().widthTemplateDesigner = this.getWidth();
        scrollRule.getCellPanelTemplate().heightTemplateDesigner = this.getHeight();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (editTemplateId > 0) {
            int result = JOptionPane.showConfirmDialog(this, "¿Está seguro de eliminar la Plantilla?.", Utilerias.getProperty(ApplicationProperties.APP_TITLE), JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION) {
                TemplateDAO tempDAO = new TemplateDAO();
                int val = tempDAO.validaEliminacionTemplate(editTemplateId);
                boolean res = val != TemplateDAO.DELETE_TEMPLATE;
                if (res) {
                    if (val == TemplateDAO.DEFAULT_TEMPLATE) {
                        JOptionPane.showMessageDialog(this, "La plantilla no se puede eliminar, ya que es predefinida.");
                    } else {
                        JOptionPane.showMessageDialog(this, "La plantilla no se puede eliminar, ya que está siendo usada.");
                    }
                    editTemplateId = 0;
                } else {
                    res = tempDAO.removeTemplate(editTemplateId);
                    if (!res) {
                        JOptionPane.showMessageDialog(this, "Ocurrió un error al eliminar.");
                    } else {
                        JOptionPane.showMessageDialog(this, "La plantilla se eliminó satisfactoriamente.");

                        jButton3.setEnabled(false);
                        populatePanel();

                        panelTemplateThums.removeAll();
                        panelTemplateThums.repaint();
                        worker.doInBackground();
                        panelTemplateThums.revalidate();

                        enableFields(false);
                        scrollRule.getCellPanelTemplate().removeAllModules();
                        cancel.setEnabled(false);
                        save.setEnabled(false);
                        save.setVisible(false);
                        jButton2.setVisible(false);
                        jButton1.setVisible(true);

                        nameTemplateSearch.setEnabled(true);
                        documentTypeSearch.setEnabled(true);
                        checkFirstPage.setEnabled(true);
                        btnTemplateSearch.setEnabled(true);

                        isTitle.setSelected(false);
                        scrollRule.getCellPanelTemplate().showContexMenu = false;

                        //modulos.clear();
                        //height.clear();
                        clearFields();
                        //height = new ArrayList();
                        scrollRule.getCellPanelTemplate().viewEditMsj = false;
                        scrollRule.getCellPanelTemplate().editMode = false;
                        editTemplateId = 0;
                        titleAdded = false;
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una plantilla para eliminar.");
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DesignerModuleDialog dialog = new DesignerModuleDialog(MainApp.getApplication().getMainFrame(), true, 0);
        dialog.setBounds(new Rectangle(this.getWidth(), this.getHeight()));//900,700
        dialog.initDesignarModule();
        Utilerias.centreDialog(dialog, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void searchModules3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchModules3KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            fillRes = false;
            filtroStr = searchModules3.getText();
            moduleCenterPanel.removeAll();
            moduleCenterPanel.repaint();
            populatePanel();
            moduleCenterPanel.revalidate();
        }
    }//GEN-LAST:event_searchModules3KeyPressed

    private void nameTemplateSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTemplateSearchKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            filtroStr = nameTemplateSearch.getText();
            if (documentTypeSearch.getSelectedItem() instanceof DocumentTypeBO) {
                type = (DocumentTypeBO) documentTypeSearch.getSelectedItem();
            } else {
                type = null;
            }

            if (type != null && type.getIddocument_type() <= 0) {
                type = null;
            }

            panelTemplateThums.removeAll();
            panelTemplateThums.repaint();
            worker.doInBackground();
            panelTemplateThums.revalidate();

            if (panelTemplateThums.getComponentCount() <= 0) {
                JOptionPane.showMessageDialog(this, "No se encontraron coincidencias de la búsqueda.");
            }
        }
    }//GEN-LAST:event_nameTemplateSearchKeyPressed

    protected void populatePanelTemp() {
        MainView.main.getProgressBar().setIndeterminate(true);
        MainView.main.getProgressBar().setVisible(true);
        worker.doInBackground();
        panelTemplateThums.revalidate();
        loadDocumentTypeCbo();
    }

    private void loadDocumentTypeCbo() {
        documentType.removeAllItems();
        documentTypeSearch.removeAllItems();

        DocumentTypeDAO daoDoc = new DocumentTypeDAO();
        List<DocumentTypeBO> listDoc = daoDoc.get(null, -1, 0);
        DocumentTypeBO boDoc = new DocumentTypeBO();
        /*Agregando valores por default al combo*/
        boDoc.setName("Seleccione");
        boDoc.setIddocument_type(-1);
        ccbox = new CCheckBox("Seleccione", null);
        ccbox.addChangeListener(new ChangeListener() {

            @Override
            public void stateChanged(ChangeEvent e) {
                ccbox.setSelected(false);
            }
        });
        documentType.addItem(ccbox);
        documentTypeSearch.addItem(boDoc);
        for (DocumentTypeBO boDoc2 : listDoc) {
            CCheckBox cc = new CCheckBox(boDoc2.toString(), boDoc2);
            cc.setSelected(false);
            documentType.addItem(cc);
            documentTypeSearch.addItem(boDoc2);
        }

    }

    private void loadDocTypeCboSearch() {
        documentTypeSearch.removeAllItems();
        DocumentTypeDAO daoDoc = new DocumentTypeDAO();
        List<DocumentTypeBO> listDoc = daoDoc.get(null, -1, 0);

        DocumentTypeBO boDoc = new DocumentTypeBO();
        boDoc.setName("Seleccione");
        boDoc.setIddocument_type(-1);

        documentTypeSearch.addItem(boDoc);
        for (DocumentTypeBO boDoc2 : listDoc) {
            documentTypeSearch.addItem(boDoc2);
        }
    }

    protected void enableFields(boolean b) {
        txtTemplateName.setEnabled(b);
        documentType.setEnabled(b);
        undo.setEnabled(b);
        scrollPanelModules.setEnabled(b);
        moduleCenterPanel.setEnabled(b);
        searchModules3.setEnabled(b);
        btnSearchModule3.setEnabled(b);
        westPanel.setEnabled(b);
        moduleNorthPanel.setEnabled(b);
    }

    private void clearFields() {
        txtTemplateName.setText(null);
        //documentType.setSelectedIndex(0);
        txtHeightTitulo.setText(null);
        //addHeightTitle.setText(null);
        for (int i = 0; i < documentType.getItemCount(); i++) {
            CCheckBox cb = (CCheckBox) documentType.getItemAt(i);
            cb.setSelected(false);
        }
    }

    protected void saveTemplate() {
        if (!scrollRule.getCellPanelTemplate().lstModule.isEmpty()) {

            if (!txtTemplateName.getText().isEmpty()) {
                if (Utilerias.isRepeatedVarcharType("TEMPLATE_NEW", "TEMPLATE_NAME", txtTemplateName.getText(), "TEMPLATE_ID", editTemplateId) == false) {
                    //if (documentType.getSelectedIndex() != 0) {

                    TemplateDAO tempDAO = new TemplateDAO();
                    TemplateBO tempBO = new TemplateBO();

                    if (scrollRule.getCellPanelTemplate().editMode) {
                        tempBO.setTemplateName(txtTemplateName.getText());
                        tempBO.setFirstPage(isTitleSelectedGloabal);
                        tempDAO.updateTemplate(editTemplateId, tempBO);

                        DocumentTypeDAO dao = new DocumentTypeDAO();
                        //Object obj = documentType.getSelectedItem();
                        //DocumentTypeBO bo = (DocumentTypeBO) obj;
                        List<DocumentTypeBO> lstDocType = getLstDocumentType();

                        dao.deleteTemplateWithDocumentType(editTemplateId);

                        for (DocumentTypeBO docType : lstDocType) {
                            List<Integer> tempDocType = dao.getTemplateByDocumentTypeId(docType.getIddocument_type());

                            if (!tempDocType.contains(new Integer(editTemplateId))) {
                                dao.linkTemplatetoDocumentType(editTemplateId, docType.getIddocument_type());
                            }
                        }

                        JOptionPane.showMessageDialog(this, "Se modifico correctamente la plantilla.");
                        isTitle.setEnabled(true);

                        clearFields();
                        enableFields(false);
                        scrollRule.getCellPanelTemplate().removeAllModules();
                        cancel.setEnabled(false);
                        save.setEnabled(false);
                        save.setVisible(false);
                        jButton1.setVisible(true);

                        nameTemplateSearch.setEnabled(true);
                        documentTypeSearch.setEnabled(true);
                        checkFirstPage.setEnabled(true);
                        btnTemplateSearch.setEnabled(true);

                        isTitle.setSelected(false);
                        scrollRule.getCellPanelTemplate().showContexMenu = false;
                        scrollRule.getCellPanelTemplate().editMode = false;
                        titleAdded = false;

                        //modulos.clear();
                        //height.clear();
                    } else {
                        ModuleBO module = new ModuleBO();
                        TemplateModuleBO tempModBO = new TemplateModuleBO();
                        List<TemplateModuleBO> lstModules = new ArrayList<>();
                        tempBO.setName(txtTemplateName.getText());
                        tempBO.setWidth((short) 580);

                        DocumentTypeDAO dao = new DocumentTypeDAO();
                        //Object obj = documentType.getSelectedItem();
                        //DocumentTypeBO bo = (DocumentTypeBO) obj;
                        List<DocumentTypeBO> lstDocType = getLstDocumentType();

                        for (int i = 0; i < scrollRule.getCellPanelTemplate().lstModule.size(); i++) {
                            module = new ModuleBO();
                            tempModBO = new TemplateModuleBO();
                            int idModulo = (int) scrollRule.getCellPanelTemplate().lstModule.get(i).getModuleId();
                            module.setModuleId(idModulo);
                            module.setOrder((short) i);
                            tempModBO.setModule(module);
                            lstModules.add(tempModBO);

                        }
                        tempBO.setModulesAsList(lstModules);
                        tempBO.setFirstPage(isTitleSelectedGloabal);

                        if (scrollRule.getCellPanelTemplate().lstModule != null) {
                            short totHeight = 0;
                            for (ModuleBO mBO : scrollRule.getCellPanelTemplate().lstModule) {
                                if (mBO.getModuleId() <= 0) {
                                    tempBO.setHeightTitle(mBO.getHeight());
                                }
                                totHeight += mBO.getHeight();
                            }
                            tempBO.setHeight(totHeight);
                        }

                        int id = tempDAO.addTemplate(tempBO);

                        for (DocumentTypeBO docType : lstDocType) {
                            dao.linkTemplatetoDocumentType(id, docType.getIddocument_type());
                        }

                        JOptionPane.showMessageDialog(this, "Se agregó correctamente la plantilla.");
                        isTitle.setEnabled(true);

                        clearFields();
                        enableFields(false);
                        scrollRule.getCellPanelTemplate().removeAllModules();
                        cancel.setEnabled(false);
                        save.setEnabled(false);
                        save.setVisible(false);
                        jButton1.setVisible(true);

                        nameTemplateSearch.setEnabled(true);
                        documentTypeSearch.setEnabled(true);
                        checkFirstPage.setEnabled(true);
                        btnTemplateSearch.setEnabled(true);

                        isTitle.setSelected(false);
                        scrollRule.getCellPanelTemplate().showContexMenu = false;
                        scrollRule.getCellPanelTemplate().editMode = false;
                        titleAdded = false;

                        //modulos.clear();
                        //height.clear();
                    }
                    //} else {
                    //    JOptionPane.showMessageDialog(this, "Seleccione un tipo de documento para la plantilla.");
                    //}
                } else {
                    JOptionPane.showMessageDialog(this, "Este nombre de plantilla se encuentra en la base de datos, ingrese otro.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Debe agregar un nombre de plantilla.");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Debe agregar por lo menos un modulo.");
        }

        //System.out.println(tempBO.getTemplateId());
    }

    private List<DocumentTypeBO> getLstDocumentType() {
        List<DocumentTypeBO> retVal = new ArrayList<>();
        for (int i = 0; i < documentType.getItemCount(); i++) {
            CCheckBox cb = (CCheckBox) documentType.getItemAt(i);
            if (cb.isSelected() && cb.getObject() != null) {
                DocumentTypeBO doc = (DocumentTypeBO) cb.getObject();
                retVal.add(doc);
            }
        }
        return retVal;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addHeightTitle;
    private javax.swing.JButton btnSearchModule3;
    private javax.swing.JButton btnTemplateSearch;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancel;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JCheckBox checkFirstPage;
    private javax.swing.JComboBox documentType;
    private javax.swing.JComboBox documentTypeSearch;
    private javax.swing.JPanel eastPanel;
    private javax.swing.JCheckBox isTitle;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel moduleCenterPanel;
    private javax.swing.JPanel moduleNorthPanel;
    private javax.swing.JTextField nameTemplateSearch;
    private javax.swing.JPanel northPanel;
    private javax.swing.JPanel panelTemplateThums;
    private javax.swing.JButton save;
    private javax.swing.JScrollPane scrollPanelModules;
    private javax.swing.JScrollPane scrollPanelTemplate;
    private javax.swing.JTextField searchModules3;
    private javax.swing.JPanel southPanel;
    private javax.swing.JTextField txtHeightTitulo;
    private javax.swing.JTextField txtTemplateName;
    private javax.swing.JButton undo;
    private javax.swing.JPanel westPanel;
    // End of variables declaration//GEN-END:variables

    class PopulatePanelWorker extends SwingWorker<ModuleBO, ModuleBO> {

        PopulatePanelWorker() {
        }

        private void addModuletoPanel(int idModule) {
            scrollRule.getCellPanelTemplate().addModuleTemplate(idModule, 0);
        }

        @Override
        protected ModuleBO doInBackground() {
            try {
                TemplateDAO tempDAO = new TemplateDAO();
                List<ModuleBO> lstModules = tempDAO.getModules();

                for (ModuleBO moduleBO : lstModules) {

                    String fileName
                            = new StringBuilder(Utilerias.getFilePath(Utilerias.PATH_TYPE.THUMB_MODULE_DIR))
                            .append(moduleBO.getModuleId())
                            //.append("_B")
                            .append(".")
                            .append(GlobalDefines.png).toString();
                    moduleBO.setTemplatePath(fileName);

                    SwingUtilities.invokeLater(new Runnable() {
                        @Override
                        public void run() {
                            if (!new File(moduleBO.getTemplatePath()).exists()) {
                                ThumbTemplate thTemp = new ThumbTemplate();
                                short hres = 30;
                                if (moduleBO.getHeight() > 350) {
                                    hres = 90;
                                }

                                thTemp.genThumbModule(moduleBO.getModuleId(), (short) 90, hres, "");
                                thTemp.genThumbModule(moduleBO.getModuleId(), moduleBO.getWidth(), moduleBO.getHeight(), "_B");
                            }
                        }
                    });

                    if (filtroStr != null && filtroStr.trim().length() > 0) {
                        if (moduleBO.getName().toUpperCase().contains(filtroStr.toUpperCase())) {
                            publish(moduleBO);
                        }
                    } else {
                        publish(moduleBO);
                    }
                }
            } catch (Exception ex) {
                Utilerias.logger(getClass()).error(ex);
            }
            return null;
        }

        @Override
        public void process(List<ModuleBO> chunks) {
            if (chunks == null) {
                return;
            }

            try {
                for (int i = 0; i < chunks.size(); i++) {
                    try {
                        final ModuleBO modBO = chunks.get(i);

                        PanelThumb pan = new PanelThumb(modBO.getModuleId(), PanelThumb.DEFAULT_WIDTH_PANEL_SIZE, PanelThumb.DEFAULT_HEIGHT_PANEL_SIZE, modBO.getTemplatePath(), modBO.getName());
                        pan.getButton().addMouseListener(new MouseAdapter() {

                            @Override
                            public void mouseClicked(MouseEvent me) {
                                if (me.getClickCount() == GlobalDefines.DEFAULT_CLICK_COUNT) {

                                    currentHeight = modBO.getHeight();

                                    if (save.isVisible()) {
                                        if (scrollRule.getCellPanelTemplate().lstModule == null) {
                                            scrollRule.getCellPanelTemplate().lstModule = new ArrayList<>();
                                            modBO.getModuleId();
                                        }

                                        if (scrollRule.getCellPanelTemplate().editMode) {
                                            scrollRule.getCellPanelTemplate().viewEditMsj = true;
                                        }

                                        totalHeight = 0;
                                        for (ModuleBO mBO : scrollRule.getCellPanelTemplate().lstModule) {
                                            if ("Titulo".equals(mBO.getName().trim()) && mBO.getWidth() == 0) {
                                                continue;
                                            }
                                            totalHeight += mBO.getHeight();
                                        }
                                        totalHeight += modBO.getHeight();

                                        if (totalHeight > getMaxHeight()) {//HEIGHT_MODEL_PX) {
                                            JOptionPane.showMessageDialog(null, "La plantilla supera el alto de una hoja, no se puede agrego el módulo. Intente con un módulo de menor tamaño");
                                            totalHeight = (short) (totalHeight - currentHeight);
                                        } else {
                                            addModuletoPanel(modBO.getModuleId());
                                        }
                                    }
                                }

                            }
                        });
                        moduleCenterPanel.add(pan);
                        moduleCenterPanel.revalidate();
                        moduleCenterPanel.updateUI();
                        fillRes = true;
                    } catch (Exception e) {
                        Utilerias.logger(getClass()).debug(e);
                    }
                }
            } catch (Exception ex) {
                Utilerias.logger(getClass()).error(ex);
            }
        }

        @Override
        protected void done() {
            MainView.main.getProgressBar().setVisible(false);
            if (fillRes == false) {
                JOptionPane.showMessageDialog(null, "No se encontraron coincidencias de la búsqueda");
            }
        }

        private short getMaxHeight() {
            if (isTitleSelectedGloabal) {
                if (scrollRule.getCellPanelTemplate().lstModule != null 
                        && scrollRule.getCellPanelTemplate().lstModule.size() > 0
                        && "Titulo".equals( scrollRule.getCellPanelTemplate().lstModule.get(0).getName() )) {
                    return (short) (GlobalDefines.DRAWABLE_HEIGHT_PH - scrollRule.getCellPanelTemplate().lstModule.get(0).getHeight());
                } else {
                    return GlobalDefines.DRAWABLE_HEIGHT_PH;
                }
            }

            return GlobalDefines.DRAWABLE_HEIGHT;
        }
    }

    class PopulatePanelTempWorker {

        private void addModuleToPanel(int idModule) {
            scrollRule.getCellPanelTemplate().addModuleTemplate(idModule, 0);
        }

        protected TemplateBO doInBackground() {
            try {
                TemplateDAO tempDAO = new TemplateDAO();
                final List<TemplateBO> lstTempBO = tempDAO.getTemplates();
                if (lstTempBO == null) {
                    return null;
                }
                for (final TemplateBO tempBO : lstTempBO) {
                    if (tempBO == null) {
                        continue;
                    }

                    String fileName
                            = new StringBuilder(Utilerias.getFilePath(Utilerias.PATH_TYPE.THUMB_TEMPLATE_DIR))
                            .append(tempBO.getTemplateId())
                            .append(".")
                            .append(GlobalDefines.png).toString();

                    tempBO.setTemplatePath(fileName);
                    if (filtroStr != null && filtroStr.trim().length() > 0) {
                        if (tempBO.getTemplateName().toUpperCase().contains(filtroStr.toUpperCase())) {
                            process(tempBO);
                        }
                    } else {
                        process(tempBO);
                    }
                }
            } catch (Exception ex) {
                Utilerias.logger(getClass()).error(ex);
            }
            return null;
        }

        public void process(TemplateBO tempBO) {
            if (tempBO == null) {
                return;
            }
            try {
                //boolean bSelected= false;
                if (type != null && type.getTemplates() != null && !type.getTemplates().contains(tempBO.getTemplateId())) {
                    return;
                }
                //if(selectedLst.contains(tempBO.getTemplateId())){
                //    bSelected=true;
                //}

                if (!new File(tempBO.getTemplatePath()).exists()) {
                    ThumbTemplate thTemp = new ThumbTemplate();
                    thTemp.genThumbTemplate(tempBO.getTemplateId(), (short) 90, (short) 90);
                }

                PanelThumb pan = new PanelThumb(
                        tempBO.getTemplateId(),
                        PanelThumb.DEFAULT_WIDTH_PANEL_SIZE,
                        PanelThumb.DEFAULT_HEIGHT_PANEL_SIZE,
                        tempBO.getTemplatePath(),
                        tempBO.getTemplateName());

                //pan.setChecked(bSelected);
                pan.getButton().addMouseListener(new MouseAdapter() {

                    @Override
                    public void mouseClicked(MouseEvent me) {
                        if (me.getClickCount() == GlobalDefines.DEFAULT_CLICK_COUNT) {

                            if (!save.isVisible()) {
                                scrollRule.getCellPanelTemplate().removeAllModules();

                                DocumentTypeDAO docDAO = new DocumentTypeDAO();
                                TemplateDAO tempDAO = new TemplateDAO();
                                TemplateBO templateBO = tempDAO.getTemplate(tempBO.getTemplateId());

                                editTemplateId = templateBO.getTemplateId();

                                txtTemplateName.setText(templateBO.getTemplateName());
                                if (templateBO.getHeightTitle() > 0) {
                                    scrollRule.getCellPanelTemplate().addModuleTemplate(0, templateBO.getHeightTitle());
                                    //isTitle.setSelected(true);
                                    titleAdded = true;
                                    addHeightTitle.setEnabled(false);
                                    txtHeightTitulo.setText("0");//(String.valueOf(Utilerias.pxToCm( templateBO.getHeightTitle(), 72)));
                                }
                                isTitle.setSelected(templateBO.isFirstPage());

                                List<Integer> lstDocTypeId = docDAO.getDocumentTypeByTemplateId(editTemplateId);
                                for (int i = 0; i < documentType.getItemCount(); i++) {
                                    CCheckBox cb = (CCheckBox) documentType.getItemAt(i);

                                    if (cb.getObject() == null) {
                                        continue;
                                    }

                                    DocumentTypeBO doc = (DocumentTypeBO) cb.getObject();
                                    boolean res = false;
                                    if (lstDocTypeId.contains(doc.getIddocument_type())) {
                                        res = true;
                                    }
                                    cb.setSelected(res);
                                }

                                List<TemplateModuleBO> lstTempModBO = templateBO.getModulesAsList();
                                if (lstTempModBO != null) {
                                    //modulos = new ArrayList();

                                    for (TemplateModuleBO tmBO : lstTempModBO) {
                                        //modulos.add(tmBO.getModuleId());
                                        addModuleToPanel(tmBO.getModuleId());
                                    }

                                    jButton2.setVisible(true);
                                    jButton1.setVisible(false);
                                    cancel.setEnabled(true);
                                    jButton3.setEnabled(true);
                                }
                            }
                        }

                    }
                }
                );
                panelTemplateThums.add(pan);
                panelTemplateThums.revalidate();
                panelTemplateThums.updateUI();
                //getPanelThumbTodoses().add(pan);
            } catch (Exception ex) {
                Utilerias.logger(getClass()).error(ex);
            }
        }
    }
}
