package com.adinfi.formateador.view;

import com.adinfi.formateador.util.Utilerias;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author Guillermo Trejo
 */
public class PanelThumb extends javax.swing.JPanel {

    public static final short MAX_WIDTH_GAP = 10;
    public static final short MAX_HEIGHT_GAP = 10;
    public static final short MIN_WIDTH_GAP = 5;
    public static final short MIN_HEIGHT_GAP = 5;
    public static final short DEFAULT_WIDTH_PANEL_SIZE = 90;
    public static final short DEFAULT_HEIGHT_PANEL_SIZE = 90;
    private JButton button;
    private String fileName;
    private String moduleName;
    private int id;
    private int panelWidth;
    private int panelHeight;
    private Image imgCurrent;
    private ImageIcon originalImageIcon;
    private ImageIcon zoomIn;
    private ImageIcon zoomOut;

    /**
     * Creates new form PanelThumb
     *
     * @param id
     * @param width
     * @param height
     * @param file
     * @param moduleName
     */
    public PanelThumb(int id, short width, short height, String file, String moduleName) {
        initComponents();
        this.id = id;
        this.panelWidth = width;
        this.panelHeight = height;
        this.fileName = file;
        this.moduleName = moduleName;
        this.setPreferredSize(new Dimension(width + MAX_WIDTH_GAP, height + MAX_HEIGHT_GAP));
        setNameLabel();
        setImage();
        initScreen();
    }

    private void setNameLabel() {
        label.setText(moduleName);
    }

    public final void setImage() {
        try {
            File file = new File(fileName);
            if (file.exists() == true) {
                imgCurrent = ImageIO.read(file);
                originalImageIcon = new ImageIcon(imgCurrent);
                this.panelWidth = originalImageIcon.getIconWidth();
                this.panelHeight = originalImageIcon.getIconHeight();
                button = new JButton(originalImageIcon);
                zoomIn = new ImageIcon(imgCurrent.getScaledInstance((panelWidth < 0 ? 90 : panelWidth) + MAX_WIDTH_GAP, (panelHeight < 0 ? 90 : panelHeight) + MAX_HEIGHT_GAP, Image.SCALE_SMOOTH));
                zoomOut = new ImageIcon(imgCurrent.getScaledInstance((panelWidth < 0 ? 90 : panelWidth) - MIN_WIDTH_GAP, (panelHeight < 0 ? 90 : panelHeight) - MIN_WIDTH_GAP, Image.SCALE_SMOOTH));
                button.revalidate();
                this.revalidate();
            }
        } catch (IOException ex) {
            Utilerias.logger(PanelThumb.class).debug(ex);
        }
    }

    protected final void initScreen() {
        getButton().addMouseListener(new MouseAdapter() {

            @Override
            public void mouseEntered(MouseEvent evt) {
                getButton().setIcon(zoomIn);
            }

            @Override
            public void mouseExited(MouseEvent evt) {
                getButton().setIcon(originalImageIcon);
            }

            @Override
            public void mousePressed(MouseEvent evt) {
                getButton().setIcon(zoomOut);
            }

            @Override
            public void mouseReleased(MouseEvent evt) {
                getButton().setIcon(zoomIn);
            }
        });
        getButton().setOpaque(false);
        getButton().setContentAreaFilled(false);
        getButton().setBorderPainted(false);
        getButton().setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        this.jpCenter.removeAll();
        this.jpCenter.add(getButton(), BorderLayout.CENTER);
        this.jpCenter.add(label, BorderLayout.SOUTH);
    }

    public void displayImage(File file) {
        imgCurrent = new ImageIcon(file.getAbsolutePath()).getImage();
        getButton().repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpCenter = new javax.swing.JPanel();
        label = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setMinimumSize(new java.awt.Dimension(1000, 1000));
        setPreferredSize(new java.awt.Dimension(1000, 1000));
        setLayout(new java.awt.BorderLayout());

        jpCenter.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jpCenter.setMinimumSize(new java.awt.Dimension(1000, 1000));
        jpCenter.setPreferredSize(new java.awt.Dimension(1000, 1000));
        jpCenter.setLayout(new java.awt.BorderLayout());

        label.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jpCenter.add(label, java.awt.BorderLayout.CENTER);

        add(jpCenter, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jpCenter;
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the fileName
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * @param fileName the fileName to set
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * @return the id
     */
    public int getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * @return the panelWidth
     */
    public int getPanelWidth() {
        return panelWidth;
    }

    /**
     * @param panelWidth the panelWidth to set
     */
    public void setPanelWidth(int panelWidth) {
        this.panelWidth = panelWidth;
    }

    /**
     * @return the panelHeight
     */
    public int getPanelHeight() {
        return panelHeight;
    }

    /**
     * @param panelHeight the panelHeight to set
     */
    public void setPanelHeight(int panelHeight) {
        this.panelHeight = panelHeight;
    }

    /**
     * @return the button
     */
    public JButton getButton() {
        return button;
    }

}
