/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.adinfi.formateador.view;

import com.adinfi.formateador.bos.ModuleBO;
import com.adinfi.formateador.dao.DocumentDAO;
import com.adinfi.formateador.dao.TemplateDAO;
import com.adinfi.formateador.util.GlobalDefines;
import com.adinfi.formateador.util.Utilerias;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;

/**
 *
 * @author Desarrollador
 */
public class PanelSearchModule extends javax.swing.JPanel {

    List<ModuleBO > lstModules=null;
    ScrIntegradorMod scrIntegrador=null;
    /**
     * Creates new form PanelSearchModule
     */
    
    /**
     * 
     * @param scrInt 
     */
    public PanelSearchModule(ScrIntegradorMod scrInt) {
        initComponents();
        this.scrIntegrador=scrInt;
        buscarModulos();
    }

    public void buscarModulos(){
        /*if( edNombre.getText()==null || edNombre.getText().isEmpty() ){
            return;
        }*/
        
        TemplateDAO tempDAO=new TemplateDAO();
        lstModules= tempDAO.searchModulesByName(edNombre.getText().trim());
        
        panThumbMod.removeAll();
        if( lstModules==null ){
            return;
        }
        
        for (ModuleBO moduleBO : lstModules) {
                    String fileName
                            = new StringBuilder(Utilerias.getFilePath(Utilerias.PATH_TYPE.THUMB_MODULE_DIR))
                            .append(moduleBO.getModuleId())
                            .append(".")
                            .append(GlobalDefines.png).toString();
                    moduleBO.setTemplatePath(fileName);
        }
       
        addModules();  
    }
    
    
       public void addModules( ) {
           if( this.lstModules==null ){
               return;
           }
             
            try {
                for ( ModuleBO modBO : this.lstModules ) {
                     
 

                    PanelThumb pan = new PanelThumb(modBO.getModuleId(), PanelThumb.DEFAULT_WIDTH_PANEL_SIZE, PanelThumb.DEFAULT_HEIGHT_PANEL_SIZE, modBO.getTemplatePath(), modBO.getName());
                    pan.getButton().addMouseListener(new MouseAdapter() {
                        final ScrIntegradorMod scrInt=scrIntegrador;
                        @Override
                        public void mouseClicked(MouseEvent me) {
                            if (me.getClickCount() == 2 ) {
                                try {
                                    
                                    scrInt.addModuleFromSearch(pan.getId());
                                    /*
                                    MainView.main.getProgressBar().setIndeterminate(true);
                                    MainView.main.getProgressBar().setVisible(true);
                                    AddModulesWorker worker = new AddModulesWorker(modBO);
                                    worker.execute(); */
                                } catch (Exception ex) {
                                    Utilerias.logger(getClass()).info(ex);
                                }
                                System.out.println("click");
                            }
                        }
                    });
                    panThumbMod.add(pan);
                }
                panThumbMod.invalidate();
                panThumbMod.repaint();
                panThumbMod.updateUI();
            } catch (Exception ex) {
                Utilerias.logger(getClass()).error(ex);
            }
        }    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        edNombre = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        panThumbMod = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setPreferredSize(new java.awt.Dimension(182, 60));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Buscar Módulo :");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, -1));

        edNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edNombreActionPerformed(evt);
            }
        });
        jPanel2.add(edNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 130, -1));

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 30, -1));

        add(jPanel2, java.awt.BorderLayout.NORTH);

        panThumbMod.setLayout(new javax.swing.BoxLayout(panThumbMod, javax.swing.BoxLayout.Y_AXIS));
        add(panThumbMod, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        buscarModulos();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void edNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edNombreActionPerformed
        // TODO add your handling code here:
       buscarModulos();
    }//GEN-LAST:event_edNombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField edNombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panThumbMod;
    // End of variables declaration//GEN-END:variables
}
