/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.adinfi.formateador.view;

import java.awt.BorderLayout;
import java.awt.Dialog;
import javax.swing.JPanel;

/**
 *
 * @author USUARIO
 */
public class PDFViewer extends javax.swing.JFrame {

    /**
     * Creates new form PDFViewer
     */
    public PDFViewer() {
        initComponents();
        setModalExclusionType(Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
    }
    
    public void setViewer(JPanel panel) {
        getContentPane().add(panel, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
