package com.adinfi.formateador.view;

import com.adinfi.formateador.bos.DocumentBO;
import com.adinfi.formateador.bos.DocumentSearchBO;
import com.adinfi.formateador.bos.DocumentTypeBO;
import com.adinfi.formateador.bos.HojaBO;
import com.adinfi.formateador.bos.IndustryBO;
import com.adinfi.formateador.bos.LanguageBO;
import com.adinfi.formateador.bos.MarketBO;
import com.adinfi.formateador.bos.ModuleBO;
import com.adinfi.formateador.bos.ObjectInfoBO;
import com.adinfi.formateador.bos.PublishStatusBO;
import com.adinfi.formateador.bos.SubjectBO;
import com.adinfi.formateador.bos.seguridad.Usuario;
import com.adinfi.formateador.dao.DocumentDAO;
import com.adinfi.formateador.dao.DocumentTypeDAO;
import com.adinfi.formateador.dao.IndustryDAO;
import com.adinfi.formateador.dao.LanguageDAO;
import com.adinfi.formateador.dao.MarketDAO;
import com.adinfi.formateador.dao.PublishStatusDAO;
import com.adinfi.formateador.dao.StatementConstant;
import com.adinfi.formateador.dao.SubjectDAO;
import com.adinfi.formateador.dao.TemplateDAO;
import com.adinfi.formateador.main.MainApp;
import com.adinfi.formateador.main.MainView;
import com.adinfi.formateador.util.ApplicationProperties;
import com.adinfi.formateador.util.GlobalDefines;
import com.adinfi.formateador.util.Utilerias;
import com.adinfi.formateador.util.UtileriasWS;
import com.adinfi.formateador.view.administration.tablemodel.ButtonEditor;
import com.adinfi.formateador.view.administration.tablemodel.ButtonRenderer;
import com.adinfi.formateador.view.administration.tablemodel.SearchTableModel;
import java.awt.BorderLayout;
import java.awt.Cursor;
import java.awt.Point;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.ExecutionException;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.JTable;
import javax.swing.SwingWorker;
import net.sourceforge.jdatepicker.impl.JDatePanelImpl;
import net.sourceforge.jdatepicker.impl.JDatePickerImpl;
import net.sourceforge.jdatepicker.impl.UtilDateModel;
import org.jdesktop.swingx.JXTable;

public class SearchDocByCriteria extends javax.swing.JPanel {

    UtilDateModel publicationDateFrom = new UtilDateModel();
    UtilDateModel publicationDateTo = new UtilDateModel();
    DlgAddDocumentsCollab dlgAddDocs = null;
    SearchDocumentWorker worker;

    /* Para paginado */
    public List<DocumentSearchBO> lstETot = null;
    public int numPag = 1;
    public int numEPP = 20;

    /**
     * Creates new form Search
     */
    public SearchDocByCriteria() {
        initComponents();
        fillCombos();
        loadDatePicker();
    }

    private void loadDatePicker() {

        JDatePanelImpl datePanel1 = new JDatePanelImpl(publicationDateFrom);
        JDatePickerImpl datePicker1 = new JDatePickerImpl(datePanel1);
        panelFecha1.add(BorderLayout.CENTER, datePicker1);

        JDatePanelImpl datePanel2 = new JDatePanelImpl(publicationDateTo);
        JDatePickerImpl datePicker2 = new JDatePickerImpl(datePanel2);
        panelFecha2.add(BorderLayout.CENTER, datePicker2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        northPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbMercado = new javax.swing.JComboBox();
        cmbIdioma = new javax.swing.JComboBox();
        cmbSubject = new javax.swing.JComboBox();
        cmbStatus = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cmbTipoDoc = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbIndustry = new javax.swing.JComboBox();
        cmbAutor = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        clave = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        panelFecha1 = new javax.swing.JPanel();
        panelFecha2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbContent = new javax.swing.JCheckBox();
        centerPanel = new javax.swing.JPanel();
        mainTablePanel = new javax.swing.JPanel();
        mainScrollPanel = new javax.swing.JScrollPane();
        footerMainTable = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        txtPage = new javax.swing.JTextField();
        docTotalesLabel = new javax.swing.JLabel();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(new java.awt.BorderLayout());

        northPanel.setName("northPanel"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setText("Mercado");
        jLabel1.setName("jLabel1"); // NOI18N

        cmbMercado.setName("cmbMercado"); // NOI18N

        cmbIdioma.setName("cmbIdioma"); // NOI18N
        cmbIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbIdiomaActionPerformed(evt);
            }
        });

        cmbSubject.setName("cmbSubject"); // NOI18N

        cmbStatus.setName("cmbStatus"); // NOI18N
        cmbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStatusActionPerformed(evt);
            }
        });

        jLabel4.setText("Estado");
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel2.setText("Tema");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText("Idioma");
        jLabel3.setName("jLabel3"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cmbMercado, 0, 293, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbSubject, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbIdioma, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbMercado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cmbIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.setName("jPanel2"); // NOI18N

        cmbTipoDoc.setName("cmbTipoDoc"); // NOI18N

        jLabel5.setText("Tipo de Documento");
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setText("Sector");
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setText("Autor");
        jLabel7.setName("jLabel7"); // NOI18N

        cmbIndustry.setName("cmbIndustry"); // NOI18N

        cmbAutor.setName("cmbAutor"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbIndustry, 0, 325, Short.MAX_VALUE)
                    .addComponent(cmbTipoDoc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbAutor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbIndustry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel3.setName("jPanel3"); // NOI18N

        jButton2.setText("Limpiar");
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel10.setText("Búsqueda");
        jLabel10.setName("jLabel10"); // NOI18N

        clave.setName("clave"); // NOI18N
        clave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                claveKeyPressed(evt);
            }
        });

        jButton1.setText("Buscar");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clave, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(clave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setName("jPanel4"); // NOI18N

        panelFecha1.setName("panelFecha1"); // NOI18N
        panelFecha1.setLayout(new java.awt.BorderLayout());

        panelFecha2.setName("panelFecha2"); // NOI18N
        panelFecha2.setLayout(new java.awt.BorderLayout());

        jLabel8.setText("Rango Fecha:");
        jLabel8.setName("jLabel8"); // NOI18N

        jLabel9.setText("a:");
        jLabel9.setName("jLabel9"); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(panelFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(panelFecha2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelFecha1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelFecha2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        cbContent.setText("Incluir contenido del Documento");
        cbContent.setName("cbContent"); // NOI18N

        javax.swing.GroupLayout northPanelLayout = new javax.swing.GroupLayout(northPanel);
        northPanel.setLayout(northPanelLayout);
        northPanelLayout.setHorizontalGroup(
            northPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(northPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(northPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(northPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(northPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cbContent))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        northPanelLayout.setVerticalGroup(
            northPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, northPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(northPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(northPanelLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(northPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbContent))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(northPanel, java.awt.BorderLayout.NORTH);

        centerPanel.setName("centerPanel"); // NOI18N
        centerPanel.setLayout(new java.awt.BorderLayout());

        mainTablePanel.setName("mainTablePanel"); // NOI18N
        mainTablePanel.setLayout(new java.awt.BorderLayout());

        mainScrollPanel.setName("mainScrollPanel"); // NOI18N
        mainTablePanel.add(mainScrollPanel, java.awt.BorderLayout.CENTER);

        centerPanel.add(mainTablePanel, java.awt.BorderLayout.CENTER);

        footerMainTable.setName("footerMainTable"); // NOI18N

        jButton3.setText("Agregar documentos");
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Agregar modulo colaborativo");
        jButton4.setName("jButton4"); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Eliminar");
        jButton5.setName("jButton5"); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("<");
        jButton6.setName("jButton6"); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText(">");
        jButton7.setName("jButton7"); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText(">|");
        jButton8.setName("jButton8"); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("|<");
        jButton9.setName("jButton9"); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        txtPage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPage.setText("1");
        txtPage.setName("txtPage"); // NOI18N

        docTotalesLabel.setText("Total de documentos:");
        docTotalesLabel.setName("docTotalesLabel"); // NOI18N

        javax.swing.GroupLayout footerMainTableLayout = new javax.swing.GroupLayout(footerMainTable);
        footerMainTable.setLayout(footerMainTableLayout);
        footerMainTableLayout.setHorizontalGroup(
            footerMainTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerMainTableLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPage, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(docTotalesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap())
        );
        footerMainTableLayout.setVerticalGroup(
            footerMainTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerMainTableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(footerMainTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton9)
                    .addComponent(txtPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(docTotalesLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        centerPanel.add(footerMainTable, java.awt.BorderLayout.SOUTH);

        add(centerPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        clear();
        doSearch(true);
    }//GEN-LAST:event_formComponentShown

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        doSearch(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbIdiomaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbIdiomaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        addDocumentsCollab();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        addModulesCollab();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int result = JOptionPane.showConfirmDialog(
                MainApp.getApplication().getMainFrame(), "¿Desea eliminar el documento?", Utilerias.getProperty(ApplicationProperties.APP_TITLE), JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            deleteDoc();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        clear();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void claveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_claveKeyPressed
        whichKeyPressed(evt);
    }//GEN-LAST:event_claveKeyPressed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        doPaginadoAdelante();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        doPaginadoAtras();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        doPaginadoAlFinal();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        doPaginadoAlInicio();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void cmbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbStatusActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbContent;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JTextField clave;
    private javax.swing.JComboBox cmbAutor;
    private javax.swing.JComboBox cmbIdioma;
    private javax.swing.JComboBox cmbIndustry;
    private javax.swing.JComboBox cmbMercado;
    private javax.swing.JComboBox cmbStatus;
    private javax.swing.JComboBox cmbSubject;
    private javax.swing.JComboBox cmbTipoDoc;
    private javax.swing.JLabel docTotalesLabel;
    private javax.swing.JPanel footerMainTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane mainScrollPanel;
    private javax.swing.JPanel mainTablePanel;
    private javax.swing.JPanel northPanel;
    private javax.swing.JPanel panelFecha1;
    private javax.swing.JPanel panelFecha2;
    private javax.swing.JTextField txtPage;
    // End of variables declaration//GEN-END:variables
    private JXTable jxTable;

    class SearchDocumentWorker extends SwingWorker<List<DocumentSearchBO>, List<DocumentSearchBO>> {

        private Exception exception;
        private final JProgressBar bar;
        private final DocumentSearchBO docSearchBO;
        private boolean firstPage;

        SearchDocumentWorker(final JProgressBar bar, DocumentSearchBO docSearchBO) {
            this.bar = bar;
            this.docSearchBO = docSearchBO;
        }

        SearchDocumentWorker(final JProgressBar bar, DocumentSearchBO docSearchBO, boolean firstPage) {
            this.bar = bar;
            this.docSearchBO = docSearchBO;
            this.firstPage = firstPage;
        }

        @Override
        protected List<DocumentSearchBO> doInBackground() {
            List<DocumentSearchBO> list = null;
            try {
                DocumentDAO dao = new DocumentDAO();
                list = dao.getDocumentByCriteria(docSearchBO);
                int y = 0;

                //se carga la lista global para el paginado. 
                lstETot = list;

                // si es primera pagina cargar valores iniciales.
                if (firstPage) {
                    list = getElementosIniciales();
                }

            } catch (Exception ex) {
                exception = ex;
                Utilerias.logger(getClass()).info(ex);
            }
            return list;
        }

        @Override
        protected void done() {
            List<DocumentSearchBO> list = null;
            try {

                list = get();

                if (list == null || list.isEmpty()) {
                    JOptionPane.showMessageDialog(MainApp.getApplication().getMainFrame(), "No se encontraron coincidencias para la búsqueda", "Buscar documentos", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (InterruptedException | ExecutionException ex) {
                Utilerias.logger(getClass()).error(ex);
                exception = ex;
            } finally {
                SearchTableModel model = new SearchTableModel(list);
                createJXTable(model);
                setRenderEditorToColumns(jxTable);
                bar.setVisible(false);
            }
        }

        private void createJXTable(SearchTableModel model) {
            if (jxTable == null) {
                jxTable = new JXTable();
                jxTable.setHorizontalScrollEnabled(true);
                jxTable.setColumnControlVisible(false);
                int margin = 5;
                jxTable.packTable(margin);
                MouseMotionAdapter mml = new MouseMotionAdapter() {

                    @Override
                    public void mouseMoved(MouseEvent e) {
                        Point p = e.getPoint();
                        if (jxTable.columnAtPoint(p) == SearchTableModel.HAND_CURSOR_COLUMN) {
                            jxTable.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
                        } else {
                            jxTable.setCursor(Cursor.getDefaultCursor());
                        }
                    }
                };
                jxTable.addMouseMotionListener(mml);
                jxTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
                mainScrollPanel.setViewportView(jxTable);
            }

            jxTable.setModel(model);
            SearchTableCellRenderer stcr = new SearchTableCellRenderer();
            jxTable.setDefaultRenderer(Object.class, stcr);
            Utilerias.formatTablex(jxTable);
        }

    }

    class SearchDocumentWorkerPaged extends SwingWorker<List<DocumentSearchBO>, List<DocumentSearchBO>> {

        final JProgressBar bar;
        List<DocumentSearchBO> docSearchBO;

        SearchDocumentWorkerPaged(final JProgressBar bar, List<DocumentSearchBO> docSearchBO) {
            this.bar = bar;
            this.docSearchBO = docSearchBO;
        }

        @Override
        protected List<DocumentSearchBO> doInBackground() throws Exception {
            return docSearchBO;
        }

        @Override
        protected void done() {
            List<DocumentSearchBO> list = null;
            try {

                list = get();

                if (list == null || list.isEmpty()) {
                    JOptionPane.showMessageDialog(MainApp.getApplication().getMainFrame(), "No se encontraron coincidencias para la búsqueda", "Buscar documentos", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (InterruptedException | ExecutionException ex) {
                Utilerias.logger(getClass()).error(ex);
            } finally {
                SearchTableModel model = new SearchTableModel(list);
                createJXTable(model);
                setRenderEditorToColumns(jxTable);
                bar.setVisible(false);
            }
        }

        private void createJXTable(SearchTableModel model) {
            if (jxTable == null) {
                jxTable = new JXTable();
                jxTable.setHorizontalScrollEnabled(true);
                jxTable.setColumnControlVisible(true);
                int margin = 5;
                jxTable.packTable(margin);
                MouseMotionAdapter mml = new MouseMotionAdapter() {

                    @Override
                    public void mouseMoved(MouseEvent e) {
                        Point p = e.getPoint();
                        if (jxTable.columnAtPoint(p) == SearchTableModel.HAND_CURSOR_COLUMN) {
                            jxTable.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
                        } else {
                            jxTable.setCursor(Cursor.getDefaultCursor());
                        }
                    }
                };
                jxTable.addMouseMotionListener(mml);
                jxTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
                mainScrollPanel.setViewportView(jxTable);
            }

            jxTable.setModel(model);
            SearchTableCellRenderer stcr = new SearchTableCellRenderer();
            jxTable.setDefaultRenderer(Object.class, stcr);
            Utilerias.formatTablex(jxTable);
        }

    }

    public List<DocumentSearchBO> getElementosIniciales() {
        List<DocumentSearchBO> retVal = null;
        numPag = 1;
        try {
            retVal = new ArrayList<>();
            if (lstETot == null || lstETot.size() < 0) {
                docTotalesLabel.setText("Total de documentos: 0");
                return retVal;
            }
            docTotalesLabel.setText("Total de documentos: " + lstETot.size());

            for (int i = 0; i < numEPP; i++) {
                if (i >= lstETot.size()) {
                    break;
                }

                retVal.add(lstETot.get(i));
            }
        } catch (Exception e) {
            Utilerias.logger(getClass()).error(e);
        }

        txtPage.setText(String.valueOf(numPag));
        return retVal;
    }

    public List<DocumentSearchBO> getElementosFinales() {
        List<DocumentSearchBO> retVal = null;

        if (lstETot == null || lstETot.size() < 0) {
            return new ArrayList<>();
        } else {
            numPag = (int) lstETot.size() / numEPP;
            int residuo = lstETot.size() % numEPP;
            if (residuo > 0) {
                numPag++;
            }

            if (numPag <= 0) {
                numPag = 1;
            }
        }

        try {
            retVal = new ArrayList<>();

            int valFin = numPag * numEPP;
            int valIni = valFin - numEPP;

            for (int i = valIni; i < valFin; i++) {
                if (i >= lstETot.size()) {
                    break;
                }

                retVal.add(lstETot.get(i));
            }
        } catch (Exception e) {
            Utilerias.logger(getClass()).error(e);
        }
        txtPage.setText(String.valueOf(numPag));
        return retVal;
    }

    public List<DocumentSearchBO> getElementosAnteriores() {
        List<DocumentSearchBO> retVal = null;

        numPag--;
        if (numPag <= 0) {
            numPag = 1;
        }

        try {
            retVal = new ArrayList<>();
            if (lstETot == null || lstETot.size() < 0) {
                return retVal;
            }

            int valFin = numPag * numEPP;
            int valIni = valFin - numEPP;

            for (int i = valIni; i < valFin; i++) {
                if (i >= lstETot.size()) {
                    break;
                }

                retVal.add(lstETot.get(i));
            }
        } catch (Exception e) {
            Utilerias.logger(getClass()).error(e);
        }
        txtPage.setText(String.valueOf(numPag));
        return retVal;
    }

    public List<DocumentSearchBO> getElementosSiguientes() {
        List<DocumentSearchBO> retVal = null;

        numPag++;

        int valFin = numPag * numEPP;
        int valIni = valFin - numEPP;

        if (lstETot != null && valIni >= lstETot.size()) {
            numPag--;
            if (numPag <= 0) {
                numPag = 1;
            }
        }

        try {
            retVal = new ArrayList<>();
            if (lstETot == null || lstETot.size() < 0) {
                return retVal;
            }

            valFin = numPag * numEPP;
            valIni = valFin - numEPP;

            for (int i = valIni; i < valFin; i++) {
                if (i >= lstETot.size()) {
                    break;
                }

                retVal.add(lstETot.get(i));
            }
        } catch (Exception e) {
            Utilerias.logger(getClass()).error(e);
        }
        txtPage.setText(String.valueOf(numPag));
        return retVal;
    }

    private void doPaginadoAdelante() {
        MainView.main.getProgressBar().setIndeterminate(true);
        MainView.main.getProgressBar().setVisible(true);
        SearchDocumentWorkerPaged workerPaged = new SearchDocumentWorkerPaged(MainView.main.getProgressBar(), getElementosSiguientes());
        workerPaged.execute();
    }

    private void doPaginadoAtras() {
        MainView.main.getProgressBar().setIndeterminate(true);
        MainView.main.getProgressBar().setVisible(true);
        SearchDocumentWorkerPaged workerPaged = new SearchDocumentWorkerPaged(MainView.main.getProgressBar(), getElementosAnteriores());
        workerPaged.execute();
    }

    private void doPaginadoAlInicio() {
        MainView.main.getProgressBar().setIndeterminate(true);
        MainView.main.getProgressBar().setVisible(true);
        SearchDocumentWorkerPaged workerPaged = new SearchDocumentWorkerPaged(MainView.main.getProgressBar(), getElementosIniciales());
        workerPaged.execute();
    }

    private void doPaginadoAlFinal() {
        MainView.main.getProgressBar().setIndeterminate(true);
        MainView.main.getProgressBar().setVisible(true);
        SearchDocumentWorkerPaged workerPaged = new SearchDocumentWorkerPaged(MainView.main.getProgressBar(), getElementosFinales());
        workerPaged.execute();
    }

    private void setRenderEditorToColumns(JXTable table) {
        table.removeColumn(table.getColumnModel().getColumn(StatementConstant.SC_2.get()));
        table.getColumn(StatementConstant.SC_9.get()).setCellRenderer(new ButtonRenderer());
        table.getColumn(StatementConstant.SC_9.get()).setCellEditor(new ButtonEditor(new JCheckBox(), jxTable, ButtonEditor.ACTION.PDF));

        table.getColumn(StatementConstant.SC_10.get()).setCellRenderer(new ButtonRenderer());
        table.getColumn(StatementConstant.SC_10.get()).setCellEditor(new ButtonEditor(new JCheckBox(), jxTable, ButtonEditor.ACTION.HTML));

        table.getColumn(StatementConstant.SC_11.get()).setCellRenderer(new ButtonRenderer());
        table.getColumn(StatementConstant.SC_11.get()).setCellEditor(new ButtonEditor(new JCheckBox(), jxTable, ButtonEditor.ACTION.EDIT_DOCUMENT));

        table.getColumn(StatementConstant.SC_12.get()).setCellRenderer(new ButtonRenderer());
        table.getColumn(StatementConstant.SC_12.get()).setCellEditor(new ButtonEditor(new JCheckBox(), jxTable, ButtonEditor.ACTION.EDIT_PUBLISH));

        table.removeColumn(table.getColumnModel().getColumn(StatementConstant.SC_13.get()));
        table.removeColumn(table.getColumnModel().getColumn(StatementConstant.SC_15.get() - 1));
    }

    private void whichKeyPressed(java.awt.event.KeyEvent evt) {
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            DocumentSearchBO docSearchBO = this.getCriteria();
            MainView.main.getProgressBar().setIndeterminate(true);
            MainView.main.getProgressBar().setVisible(true);
            SearchDocumentWorker worker = new SearchDocumentWorker(MainView.main.getProgressBar(), docSearchBO);
            worker.execute();
            evt.consume();
        }
    }

    private PublishStatusBO defStatus;

    public String convertDateFormat(String date, String formatIn, String formatOut) throws ParseException {

        String outFormat;
        SimpleDateFormat inFormat = new SimpleDateFormat(formatIn);
        Date d = inFormat.parse(date);
        inFormat.applyPattern(formatOut);
        outFormat = inFormat.format(d);

        return outFormat;
    }

    private void fillCombos() {

        MarketDAO dao = new MarketDAO();
        List<MarketBO> list = dao.get(null);
        MarketBO bo_ = new MarketBO();
        /*Agregando valores por default al combo*/
        bo_.setName("Todos");
        bo_.setIdMiVector_real("-1");
        cmbMercado.addItem(bo_);
        for (MarketBO bo : list) {
            cmbMercado.addItem(bo);
        }

        DocumentTypeDAO daoDoc = new DocumentTypeDAO();
        List<DocumentTypeBO> listDoc = daoDoc.get(null, -1, 0);
        DocumentTypeBO boDoc = new DocumentTypeBO();
//      Agregando valores por default al combo
        boDoc.setName("Todos");
        boDoc.setIddocument_type(-1);
        cmbTipoDoc.addItem(boDoc);
        if (listDoc != null) {
            for (DocumentTypeBO boDoc2 : listDoc) {
                cmbTipoDoc.addItem(boDoc2);
            }
        }

        LanguageDAO lanDao = new LanguageDAO();
        List<LanguageBO> listLan = lanDao.get(null);
        LanguageBO lanBO = new LanguageBO();
//        Agregando valores por default al combo
        lanBO.setName("Todos");
        lanBO.setIdLanguage(-1);
        cmbIdioma.addItem(lanBO);
        for (LanguageBO lanBO2 : listLan) {
            cmbIdioma.addItem(lanBO2);
        }
        SubjectDAO daoSubject = new SubjectDAO();
        List<SubjectBO> listSubject = daoSubject.get(null);
        SubjectBO suBO = new SubjectBO();
        suBO.setName("Todos");
        suBO.setIdSubject(-1);
        cmbSubject.addItem(suBO);
        for (SubjectBO b : listSubject) {
            cmbSubject.addItem(b);
        }

        IndustryDAO daoIndustry = new IndustryDAO();
        List<IndustryBO> industryBO = daoIndustry.get(null);
        IndustryBO iBO = new IndustryBO();
        iBO.setName("Todos");
        iBO.setIdIndustry(-1);
        cmbIndustry.addItem(iBO);
        for (IndustryBO o : industryBO) {
            cmbIndustry.addItem(o);
        }

        PublishStatusDAO pubDAO = new PublishStatusDAO();
        List<PublishStatusBO> listPubStatus = pubDAO.get();
        PublishStatusBO statusBO = new PublishStatusBO();
        statusBO.setName("Todos");
        statusBO.setIdpublish_status(-1);
        cmbStatus.addItem(statusBO);
        for (PublishStatusBO o : listPubStatus) {
            if (o.getName().equalsIgnoreCase("Enviado")) {
                defStatus = o;
            }
            cmbStatus.addItem(o);
        }

        /*if (defStatus != null) {
            cmbStatus.setSelectedItem(defStatus);
        }*/

        List<Usuario> listAuthor = UtileriasWS.getAuthor();
        Usuario u = new Usuario();
        u.setNombre("Todos");
        u.setUsuarioId(-1);
        cmbAutor.addItem(u);
        for (Usuario o : listAuthor) {
            cmbAutor.addItem(o);
        }
    }

    private void clear() {
        cmbSubject.setSelectedIndex(0);
        cmbIdioma.setSelectedIndex(0);
        cmbMercado.setSelectedIndex(0);
        cmbTipoDoc.setSelectedIndex(0);
        cmbIndustry.setSelectedIndex(0);
        cmbStatus.setSelectedIndex(0);
        cmbAutor.setSelectedIndex(0);
        clave.setText("");
        publicationDateFrom.setValue(null);
        publicationDateTo.setValue(null);
        /*if (defStatus != null) {
            cmbStatus.setSelectedItem(defStatus);
        }*/

        SearchTableModel model = new SearchTableModel(new ArrayList<DocumentSearchBO>());
        if (jxTable != null) {
            jxTable.setModel(model);
            Utilerias.formatTablex(jxTable);
        }

    }

    public DocumentSearchBO getCriteria() {
        DocumentSearchBO docSearchBO = new DocumentSearchBO();

        SubjectBO subjectBO = (SubjectBO) cmbSubject.getSelectedItem();
        if (subjectBO != null) {
            docSearchBO.setIdSubject(subjectBO.getIdSubject());
        }
        LanguageBO lanBO = (LanguageBO) cmbIdioma.getSelectedItem();
        if (lanBO != null) {
            docSearchBO.setIdLanguage(lanBO.getIdLanguage());
        }
        MarketBO marketBo = (MarketBO) cmbMercado.getSelectedItem();
        if (marketBo != null) {
            docSearchBO.setIdMarket(Integer.parseInt(marketBo.getIdMiVector_real()));
        }
        DocumentTypeBO docTypeBO = (DocumentTypeBO) cmbTipoDoc.getSelectedItem();
        if (docTypeBO != null) {
            docSearchBO.setIdDocType(docTypeBO.getIddocument_type());
        }
        IndustryBO industryBO = (IndustryBO) cmbIndustry.getSelectedItem();
        if (industryBO != null) {
            docSearchBO.setIdIndustry(industryBO.getIdIndustry());
        }
        PublishStatusBO statusPublishBO = (PublishStatusBO) cmbStatus.getSelectedItem();
        if (statusPublishBO != null) {
            docSearchBO.setIdStatus(statusPublishBO.getIdpublish_status());
        }

        Usuario usuario = (Usuario) cmbAutor.getSelectedItem();
        if (usuario != null) {
            docSearchBO.setIdAuthor(usuario.getUsuarioId());
        }

        String palabraClave = clave.getText();
        if (palabraClave != null && palabraClave.isEmpty() == false) {
            docSearchBO.setCriteria(palabraClave);
        }
        Date from = publicationDateFrom.getValue();
        String publicationFrom = "";
        if (from != null) {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            publicationFrom = sdf.format(from);
        }
        docSearchBO.setDocPublicationDateFrom(publicationFrom);

        Date to = publicationDateTo.getValue();
        String publicationTo = "";
        if (to != null) {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            publicationTo = sdf.format(to);
        }
        docSearchBO.setDocPublicationDateTo(publicationTo);

        docSearchBO.setSearchByContent(cbContent.isSelected());

        return docSearchBO;
    }

    private void deleteDoc() {
        SearchTableModel model = (SearchTableModel) jxTable.getModel();
        Object[][] data = model.getData();
        if (data == null) {
            return;
        }

        List<DocumentSearchBO> lstDocs = model.getList();
        List<DocumentSearchBO> lstDocs2 = new ArrayList<>();
        DocumentSearchBO docBO;
        Object[] row = null;
        Boolean checked = false;
        for (int i = 0; i < data.length; i++) {
            row = data[i];
            if (row == null) {
                continue;
            }
            checked = (Boolean) row[SearchTableModel.HAND_CURSOR_COLUMN];

            if (checked == true) {
                docBO = lstDocs.get(i);
                DocumentDAO docDAO = new DocumentDAO();
                if (docBO != null) {
                    try {
                        if(docBO.getVersion() == (-5)){
                            docDAO.eliminarDocAttach(docBO.getDocumentId());
                        }else{
                            DocumentBO documentBO = docDAO.getDocument(docBO.getDocumentId(), docBO.getVersion(),false);
                            Map<Integer, HojaBO> mapHojas = documentBO.getMapHojas();
                            if (mapHojas != null) {
                                StringBuilder sbIdHojas = new StringBuilder();
                                final Set<Integer> keySet = mapHojas.keySet();
                                for (Integer keySet1 : keySet) {
                                    HojaBO hojaBO = mapHojas.get(keySet1);
                                    sbIdHojas.append(hojaBO.getHoja()).append(",");
                                }

                                try {
                                    docDAO.eliminarHojas(sbIdHojas.toString().substring(0, sbIdHojas.toString().lastIndexOf(",")), documentBO);
                                } catch (Exception e) {
                                    Utilerias.logger(getClass()).error(e);
                                }

                            }
                            docDAO.eliminarDocumento(documentBO.getDocumentId());
                            docDAO.deleteConcatObjsDocument(documentBO.getDocumentId());
                        }

                    } catch (SQLException e) {
                        Utilerias.logger(getClass()).error(e);
                    }
                }
            } else {
                lstDocs2.add(lstDocs.get(i));
            }
        }

        model = new SearchTableModel(lstDocs2);
        createJXTable(model);
        setRenderEditorToColumns(jxTable);
        //jxTable.setModel(model);
        //Utilerias.formatTablex(jxTable);
    }
    
            private void createJXTable(SearchTableModel model) {
            if (jxTable == null) {
                jxTable = new JXTable();
                jxTable.setHorizontalScrollEnabled(true);
                jxTable.setColumnControlVisible(false);
                int margin = 5;
                jxTable.packTable(margin);
                MouseMotionAdapter mml = new MouseMotionAdapter() {

                    @Override
                    public void mouseMoved(MouseEvent e) {
                        Point p = e.getPoint();
                        if (jxTable.columnAtPoint(p) == SearchTableModel.HAND_CURSOR_COLUMN) {
                            jxTable.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
                        } else {
                            jxTable.setCursor(Cursor.getDefaultCursor());
                        }
                    }
                };
                jxTable.addMouseMotionListener(mml);
                jxTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
                mainScrollPanel.setViewportView(jxTable);
            }

            jxTable.setModel(model);
            SearchTableCellRenderer stcr = new SearchTableCellRenderer();
            jxTable.setDefaultRenderer(Object.class, stcr);
            Utilerias.formatTablex(jxTable);
        }


    public void addModulesCollab() {
        SearchTableModel model = (SearchTableModel) jxTable.getModel();
        Object[][] data = model.getData();
        if (data == null) {
            return;
        }

        List<DocumentSearchBO> lstDocs = model.getList();
        Map<Integer, String> lstModAdd = null;
        List<DocumentSearchBO> lstDocsAdd = null;
        DocumentSearchBO docBO;
        Object[] row = null;
        Boolean checked = false;
        List<Integer> lModule = new ArrayList<>();
        for (int i = 0; i < data.length; i++) {
            row = data[i];
            if (row == null) {
                continue;
            }
            checked = (Boolean) row[SearchTableModel.HAND_CURSOR_COLUMN];
            if (lstDocsAdd == null) {
                lstDocsAdd = new ArrayList<>();
            }
            if (checked == true) {

                docBO = lstDocs.get(i);
                DocumentDAO docDAO = new DocumentDAO();
                TemplateDAO tempDAO = new TemplateDAO();
                if (docBO != null) {
                    try {
                        DocumentBO documentBO = docDAO.getDocument(docBO.getDocumentId(), docBO.getVersion(),false);
                        if (documentBO != null) {
                            if (documentBO.isCollaborative()) {
                                JOptionPane.showMessageDialog(this, "No se puede agregar modulos del documento " + documentBO.getDocument_Name() + " por que fue generado en integrador de documentos", "Agregar módulos ", JOptionPane.OK_OPTION);
                                continue;
                            } else {
                                DocumentTypeDAO docTypeDAO = new DocumentTypeDAO();
                                List<Integer> lDocTypes = docTypeDAO.getTemplateByDocumentTypeId(documentBO.getIdDocument_Type());
                                if (lDocTypes != null && lDocTypes.contains(16)) {
                                    JOptionPane.showMessageDialog(this, "Los módulos de una Plantilla 16 no puedes ser agregados", "Agregar módulos ", JOptionPane.OK_OPTION);
                                    return;
                                }
                                List<Integer> modPlan16 = new ArrayList<>();
                                modPlan16.add(GlobalDefines.OBJ_TYPE_CALENDAR);
                                modPlan16.add(GlobalDefines.OBJ_TYPE_CALENDAR_MONTH);
                                modPlan16.add(GlobalDefines.OBJ_TYPE_CALENDAR_WEEK);
                                if (documentBO.getMapHojas() != null) {
                                    Map<Integer, HojaBO> mapHojas = documentBO.getMapHojas();
                                    if (mapHojas != null) {
                                        if (lstModAdd == null) {
                                            lstModAdd = new HashMap<>();
                                        }
                                        for (Iterator<HojaBO> it = mapHojas.values().iterator(); it.hasNext();) {
                                            HojaBO hojaBO = it.next();
                                            for (ModuleBO moduleBO : hojaBO.getLstModules()) {
                                               // if (!lModule.contains(moduleBO.getModuleId())) {
                                                    ModuleBO modName = tempDAO.getModule(moduleBO.getModuleId());
                                                    boolean agregar = true;
                                                    if (modName.getRootSection() != null
                                                            && modName.getRootSection().getLstObjects() != null) {
                                                        for (ObjectInfoBO oiBO : modName.getRootSection().getLstObjects()) {
                                                            if (modPlan16.contains(oiBO.getObjType())) {
                                                                agregar = false;
                                                                break;
                                                            }
                                                        }

                                                    }
                                                    if (agregar) {
                                                        lModule.add(moduleBO.getModuleId());
                                                        lstModAdd.put(moduleBO.getDocumentModuleId(), modName.getName());
                                                    } else {
                                                        JOptionPane.showMessageDialog(this, "Los módulos relacionadoss con una Plantilla 16 no puedes ser agregados", "Agregar módulos ", JOptionPane.OK_OPTION);
                                                    }
                                               // }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    } catch (SQLException e) {

                    }
                    lstDocsAdd.add(docBO);
                }
            }

        }

        if (lstDocsAdd == null || lstDocsAdd.size() <= 0) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar los documentos para agregar", "Agregar módulos ", JOptionPane.OK_OPTION);
            return;
        }
        if (lstModAdd == null || lstModAdd.size() <= 0) {
            JOptionPane.showMessageDialog(this, "No hay modulos que agregar", "Agregar módulos ", JOptionPane.OK_OPTION);
            return;
        }
        lModule.clear();
        showDlgAddModuleColl(lstModAdd);
    }

    private void showDlgAddModuleColl(Map<Integer, String> lDocModCo) {
        DlgModuloColaborativo dlgModCol = new DlgModuloColaborativo(MainApp.getApplication().getMainFrame(), true, lDocModCo.size() == 1);
        dlgModCol.setlDocModCollab(lDocModCo);
        dlgModCol.setAdd(true);
        Utilerias.centreDialog(dlgModCol, true);
        dlgModCol.setIconImage(Utilerias.getImage(Utilerias.ICONS.APP_RIBBON_ICON));
        dlgModCol.setVisible(true);
    }

    public void addDocumentsCollab() {

        SearchTableModel model = (SearchTableModel) jxTable.getModel();
        Object[][] data = model.getData();
        if (data == null) {
            return;
        }

        List<DocumentSearchBO> lstDocs = model.getList();
        List<DocumentSearchBO> lstDocsAdd = null;
        DocumentSearchBO docBO;
        Object[] row = null;
        Boolean checked = false;
        for (int i = 0; i < data.length; i++) {
            row = data[i];
            if (row == null) {
                continue;
            }
            checked = (Boolean) row[  SearchTableModel.HAND_CURSOR_COLUMN];

            if (checked == true) {
                docBO = lstDocs.get(i);
                if (lstDocsAdd == null) {
                    lstDocsAdd = new ArrayList<>();
                }
                docBO = lstDocs.get(i);
                lstDocsAdd.add(docBO);
            }

        }

        if (lstDocsAdd == null || lstDocsAdd.size() <= 0) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar los documentos para agregar", "Agregar documentos ", JOptionPane.OK_OPTION);
            return;
        }

        showDlgDocsCollab(lstDocsAdd);
    }

    public void showDlgDocsCollab(List<DocumentSearchBO> lstDocsAdd) {
        if (dlgAddDocs == null) {
            dlgAddDocs = new DlgAddDocumentsCollab(MainApp.getApplication().getMainFrame(), true);
        }
        dlgAddDocs.setTitle("Agregar documentos colaborativos ");
        dlgAddDocs.setDocumentsAdd(lstDocsAdd);
        dlgAddDocs.setLocation(200, 200);
        dlgAddDocs.setVisible(true);

    }

    private void doSearch(boolean firstPage) {
        DocumentSearchBO docSearchBO = new DocumentSearchBO();
        if (publicationDateFrom.getValue() != null && publicationDateTo.getValue() != null) {
            Date from = publicationDateFrom.getValue();
            Date to = publicationDateTo.getValue();

            String day_from = String.valueOf(publicationDateFrom.getDay());
            String month_from = String.valueOf(publicationDateFrom.getMonth() + 1);
            String year_from = String.valueOf(publicationDateFrom.getYear());
            String theDate_from = day_from + "/" + month_from + "/" + year_from;

            String day_to = String.valueOf(publicationDateTo.getDay());
            String month_to = String.valueOf(publicationDateTo.getMonth() + 1);
            String year_to = String.valueOf(publicationDateTo.getYear());
            String theDate_to = day_to + "/" + month_to + "/" + year_to;

            String d_from;
            String d_to;
            Date d_from_formated = null;
            Date d_to_formated = null;

            try {
                d_from = convertDateFormat(theDate_from, "dd/MM/yyyy", "yyyy-MM-dd");
                d_to = convertDateFormat(theDate_to, "dd/MM/yyyy", "yyyy-MM-dd");

                d_from_formated = new SimpleDateFormat("yyyy-MM-dd").parse(d_from);
                d_to_formated = new SimpleDateFormat("yyyy-MM-dd").parse(d_to);

            } catch (ParseException ex) {
                Utilerias.logger(getClass());
            }

            if (d_to_formated != null && d_from_formated != null) {
                if (d_to_formated.before(d_from_formated)) {
                    Utilerias.showMessage(MainApp.getApplication().getMainFrame(), "La fecha fin no puede ser mayor a la fecha inicio", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
        }

        docSearchBO = this.getCriteria();

        MainView.main.getProgressBar().setIndeterminate(true);
        MainView.main.getProgressBar().setVisible(true);

        worker = new SearchDocumentWorker(MainView.main.getProgressBar(), docSearchBO, firstPage);

        try {
            worker.execute();
        } catch (java.util.concurrent.CancellationException e) {
            Utilerias.logger(getClass()).info(e);
        }
    }

}
