package com.adinfi.formateador.view.publish;
/**
 *
 * @author USUARIO
 */
public class ItemPanel extends javax.swing.JPanel {

    private SendPublish sendPublish;
    private SendPublishAttachment sendPublishAttachment;
    private String path;
    private boolean isAttachment;

    /**
     * Creates new form ItemPanel
     *
     * @param label
     * @param path
     * @param sendPublish
     * @param routePath
     */
    public ItemPanel(String label, String path, SendPublish sendPublish,String routePath) {
        initComponents();
        this.jLabel2.setText(label);
        this.jLabel2.setName(path);
        this.jLabel2.setToolTipText(routePath);
        this.sendPublish = sendPublish;
        this.path = path;
    }
    
        public ItemPanel(String label, String path, SendPublishAttachment sendPublishAttachment, boolean isAttachment) {
        initComponents();
        this.jLabel2.setText(label);
        this.jLabel2.setToolTipText(path);
        this.jLabel2.setName(path);
        this.sendPublishAttachment = sendPublishAttachment;
        this.path = path;
        this.isAttachment = isAttachment;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setAutoscrolls(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        jLabel2.setName("jLabel2"); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close-icon.jpg"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String path = this.jLabel2.getName();
//        
//        
//        this.removeAll();
//        this.repaint();
//        this.updateUI();

        if(isAttachment == false){
            sendPublish.removeElementfromContainer(path);
        }else{
            sendPublishAttachment.removeElementfromContainer(path);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        System.out.println(jLabel2.getToolTipText());
    }//GEN-LAST:event_formFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the path
     */
    public String getPath() {
        return path;
    }

    /**
     * @param path the path to set
     */
    public void setPath(String path) {
        this.path = path;
    }
}
